/* GENERATED by tools/build-catalog.py */
  /* 표시 언어. 카탈로그의 나머지와 같은 규칙이고 같은 키를 읽는다 — 카탈로그에서
     일본어로 보던 사람이 덱을 열었을 때 액자만 한국어로 돌아가면 안 된다. */
  (function () {
    var D = window.PODO_VIEW || {};
    var I18N = window.PODO_I18N || {};
    var LOCALES = ["ko", "ja", "en"], KEY = "podo-catalog-locale";
    var TOC = window.PODO_TOC || null;
    var L = "ja";
    try { var v = localStorage.getItem(KEY); if (LOCALES.indexOf(v) >= 0) L = v; } catch (e) {}

    function tr(sec, key) {
      var row = (I18N[sec] || {})[key] || {};
      return row[L] || row.ko || "";
    }
    function loc(o) { return !o ? "" : (o[L] || o.ko || o.en || o.ja || ""); }
    function lvName(lv) {
      var row = (I18N.level || {})[lv];
      return (row && row[L]) || lv;
    }
    function el(tag, cls, text) {
      var n = document.createElement(tag);
      if (cls) n.className = cls;
      if (text != null) n.textContent = text;
      return n;
    }

    /* 차례는 한 번만 짓는다. 표시 언어를 바꿀 때 다시 지으면 펼쳐 둔 묶음이 도로 닫힌다 —
       그래서 글자만 갈아 끼우도록 만들 때 각 자리를 적어 둔다. */
    var paints = [];
    function buildRail() {
      var list = document.getElementById("list");
      if (!TOC) { document.getElementById("rail").hidden = true;
                  document.getElementById("toc").hidden = true; return; }
      TOC.forEach(function (c) {
        var box = list, here = c.l.some(function (r) { return r.c === D.course && r.s === D.lesson; });
        if (c.group) {
          var d = el("details", "grp"); d.open = here;
          var sm = document.createElement("summary");
          var lv = el("span", "lv"), nm = el("span", "nm"), n = el("span", "n");
          sm.appendChild(lv); sm.appendChild(nm); sm.appendChild(n);
          d.appendChild(sm); list.appendChild(d); box = d;
          paints.push(function () {
            lv.textContent = lvName(c.lv);
            nm.textContent = loc(c.n);
            /* 세는 말이 붙는 자리. 한국어·일본어는 붙여 쓰고 영어는 띄어 쓴다. */
            n.textContent = c.l.length + (L === "en" ? " " : "") + tr("ui", "lessonWord");
          });
        }
        /* 묶이지 않은 코스는 두 가지다. 과가 하나뿐이라 묶을 것이 없는 코스(체험)는
           그 줄이 곧 코스이므로 레벨로 부르고, 코스가 하나뿐인 트랙(한글 떼기)은
           줄마다 과가 다르므로 여느 때처럼 과 번호로 부른다. */
        var byLevel = !c.group && c.l.length === 1;
        c.l.forEach(function (r) {
          var a = el("a", byLevel ? "row row--solo" : "row");
          a.href = r.h;
          var b = el("b"), t = el("span", "t");
          a.appendChild(b); a.appendChild(t);
          if (r.c === D.course && r.s === D.lesson) a.setAttribute("aria-current", "page");
          box.appendChild(a);
          paints.push(function () {
            b.textContent = byLevel ? lvName(c.lv) : ("0" + r.w).slice(-2);
            t.textContent = loc(r.t);
          });
        });
      });
    }

    function foot() {
      var box = document.getElementById("foot");
      box.textContent = "";
      [["prev", D.prev], ["next", D.next]].forEach(function (pair) {
        var dir = pair[0], o = pair[1];
        var arrow = dir === "prev" ? "M10 3L5 8l5 5" : "M6 3l5 5-5 5";
        var svg = '<svg viewBox="0 0 16 16" width="13" height="13" fill="none" stroke="currentColor"'
          + ' stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
          + '<path d="' + arrow + '"/></svg>';
        var label = tr("ui", dir === "prev" ? "prevLesson" : "nextLesson");
        var node;
        if (o) {
          node = document.createElement("a");
          node.href = o.h;
          node.title = lvName(o.lv) + " · " + loc(o.t);
        } else {
          node = document.createElement("span");
          label = tr("ui", "none");
        }
        node.innerHTML = dir === "prev" ? svg + " " + label : label + " " + svg;
        box.appendChild(node);
      });
    }

    function segs() {
      var slots = document.getElementById("slots");
      slots.textContent = "";
      D.slots.forEach(function (s) {
        var a = el("a", null, tr("ui", s === "prestudy" ? "slotPrestudy" : "slotLecture"));
        a.href = s + ".html";
        if (s === D.slot) a.setAttribute("aria-current", "page");
        slots.appendChild(a);
      });
      var bar = document.getElementById("loc");
      bar.setAttribute("aria-label", tr("locale", "label"));
      bar.textContent = "";
      LOCALES.forEach(function (c) {
        var b = el("button", null, ((I18N.locale[c] || {})[c] || c));
        b.type = "button";
        b.setAttribute("data-loc", c);
        b.setAttribute("aria-pressed", String(c === L));
        bar.appendChild(b);
      });
    }

    function phoneMenu() {
      var m = document.getElementById("phone");
      m.textContent = "";
      function row(mark, text, href, sub, cur) {
        var a = document.createElement("a");
        a.href = href;
        var b = el("b", null, mark);
        a.appendChild(b);
        a.appendChild(document.createTextNode(text));
        if (sub) a.appendChild(el("span", null, " " + sub));
        if (cur) a.setAttribute("aria-current", "page");
        m.appendChild(a);
        return a;
      }
      row("←", loc(D.track), document.getElementById("track").href);
      D.slots.forEach(function (s) {
        if (s === D.slot) return;
        row("", tr("ui", s === "prestudy" ? "slotPrestudy" : "slotLecture"), s + ".html");
      });
      var f = row("", tr("ui", "fullScreen"), document.getElementById("full").href);
      f.target = "_blank"; f.rel = "noopener";
      LOCALES.forEach(function (c) {
        var a = row(((I18N.locale[c] || {})[c] || c), (I18N.locale[c] || {})[L] || c, "#",
                    null, c === L);
        a.addEventListener("click", function (e) { e.preventDefault(); setLocale(c); });
      });
    }

    function paint() {
      document.documentElement.lang = L;
      document.querySelectorAll("[data-i18n]").forEach(function (e) {
        var p = e.getAttribute("data-i18n").split("."), v = tr(p[0], p[1]);
        if (v) e.textContent = v;
      });
      document.querySelectorAll("[data-i18n-label]").forEach(function (e) {
        var p = e.getAttribute("data-i18n-label").split("."), v = tr(p[0], p[1]);
        if (v) e.setAttribute("aria-label", v);
      });
      var name = loc(D.title) || D.titleKo;
      var slot = tr("ui", D.slot === "prestudy" ? "slotPrestudy" : "slotLecture");
      document.getElementById("track").textContent = loc(D.track);
      document.getElementById("lv").textContent = lvName(D.level);
      document.getElementById("here").textContent = ("0" + D.week).slice(-2) + " · " + name;
      document.getElementById("pos").textContent = D.pos + " / " + D.total;
      document.title = name + " · " + slot + " · PODO";
      var frame = document.getElementById("deck");
      if (frame) frame.title = name + " · " + slot;
      paints.forEach(function (f) { f(); });
      segs();
      foot();
      phoneMenu();
    }

    function setLocale(c) {
      if (c === L) return;
      L = c;
      try { localStorage.setItem(KEY, L); } catch (e) {}
      paint();
    }

    document.getElementById("loc").addEventListener("click", function (e) {
      var b = e.target.closest("button[data-loc]");
      if (b) setLocale(b.dataset.loc);
    });

    buildRail();
    paint();

    /* 지금 과가 116줄 중 어디에 있든 보이는 자리에서 시작한다. */
    var list = document.getElementById("list"), cur = list.querySelector('[aria-current="page"]');
    if (cur) list.scrollTop = cur.offsetTop - list.clientHeight / 2 + cur.offsetHeight / 2;

    /* 열림·닫힘은 사람이 고른 값이라 기억한다. 고른 적이 없으면 창 너비가 정한다 —
       차례가 교재를 덮지 않는 넓이에서만 처음부터 열려 있다. */
    var btn = document.getElementById("toc"), body = document.body;
    function toc(open) {
      body.classList.toggle("toc-off", !open);
      btn.setAttribute("aria-expanded", String(open));
    }
    toc(!body.classList.contains("toc-off"));
    btn.addEventListener("click", function () {
      var open = body.classList.contains("toc-off");
      try { localStorage.setItem("podo-catalog-toc", open ? "1" : "0"); } catch (e) {}
      toc(open);
    });
    document.getElementById("scrim").addEventListener("click", function () { toc(false); });
    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape" && window.innerWidth < 1080
          && !body.classList.contains("toc-off")) toc(false);
    });

    /* ⋯ 하나짜리 팝오버. 폰에서만 보인다. */
    var more = document.getElementById("morebtn"), menu = document.getElementById("phone");
    more.addEventListener("click", function (e) {
      e.stopPropagation();
      var open = menu.hidden;
      menu.hidden = !open;
      if (!open) return;
      var r = more.getBoundingClientRect();
      menu.style.top = (r.bottom + 6) + "px";
      menu.style.left = Math.max(8, Math.min(r.left, window.innerWidth - menu.offsetWidth - 12)) + "px";
    });
    document.addEventListener("click", function () { menu.hidden = true; });
  })();

  /* 덱 파일은 룸에서 열리는 그대로라 손대지 않는다 — 액자 안에서 막대만 감춘다.

     shared/css/lesson-card.css 는 `scrollbar-gutter: stable` 로 세로 막대 자리를 항상 열어
     둔다. 룸에서는 그게 맞다 — 페이지마다 높이가 달라서, 막대가 나타났다 사라질 때마다
     가운데 480px 단이 좌우로 흔들리기 때문이다. 그런데 자리를 예약하면 브라우저가
     겹침(overlay) 막대를 포기하고 늘 보이는 막대를 그려서, 액자 바깥 막대와 나란히 둘이
     된다 — 그러면 둘 중 어느 것이 교재를 넘기는 것인지 알 수 없다.

     예약을 풀고 막대 자체도 감춘다. 넘치는 페이지에서 아래에 더 있다는 표시가 사라지지만,
     교재를 넘기는 것은 막대가 아니라 페이저이고 스크롤은 그대로 된다. 덱과 이 페이지는
     같은 출처라 스타일 한 줄을 넣어 줄 수 있다. */
  (function () {
    var frame = document.getElementById("deck");
    function hideBars() {
      try {
        var doc = frame.contentDocument;
        if (!doc || !doc.head) return;
        var style = doc.createElement("style");
        style.textContent =
          "html{scrollbar-gutter:auto;scrollbar-width:none}" +
          "html::-webkit-scrollbar,body::-webkit-scrollbar{width:0;height:0}";
        doc.head.appendChild(style);
      } catch (err) { /* 다른 출처면 그냥 둔다 — 막대가 보일 뿐 동작은 같다 */ }
    }
    frame.addEventListener("load", hideBars);
    hideBars();
  })();
