#!/usr/bin/env python3
"""Build compact proofreading packets from authored lesson HTML.

The HTML deck remains the only source of truth.  This tool emits a lossless
projection of the text that needs editorial review while omitting runtime
markup, repeated controls, scripts, styles and assets.

    python3 tools/authoring/kr/build_proofreading_packets.py \
        sandbox/drafts/kr/tracks/4-freetalking

    python3 tools/authoring/kr/build_proofreading_packets.py \
        sandbox/drafts/kr/tracks/4-freetalking --check

Review issues can be checked against the current source before anyone edits a
deck:

    python3 tools/authoring/kr/build_proofreading_packets.py \
        sandbox/drafts/kr/tracks/4-freetalking --validate-issues issues.jsonl

After an approved issue file has been applied, verify that every cited field now
equals its suggestion (the original source hash is retained as audit history):

    python3 tools/authoring/kr/build_proofreading_packets.py \
        sandbox/drafts/kr/tracks/4-freetalking --verify-applied issues.jsonl

If a non-overlapping bulk/shared-text edit changes whole-file hashes while a
review is pending, refresh only those hashes after proving every cited locator
still contains its original `current` text:

    python3 tools/authoring/kr/build_proofreading_packets.py \
        sandbox/drafts/kr/tracks/4-freetalking --refresh-issue-hashes issues.jsonl
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys
import urllib.parse
from collections import OrderedDict
from dataclasses import dataclass, field
from html.parser import HTMLParser

import plan_courses
import track_parsers


KOREAN = pathlib.Path(__file__).resolve().parents[3] / "sandbox/drafts/kr"
REPO = pathlib.Path(__file__).resolve().parents[3]
FORMAT_VERSION = 1
GENERATOR = "tools/authoring/kr/build_proofreading_packets.py"
GENERATED = f"Generated by `{GENERATOR}` — do not edit this file."
GENERIC_TRACKS = {"1-hangul", "2-core-patterns", "3-contextual-korean"}
PAGE_ORDER = [
    "lesson-goal", "source", "lesson-style", "talk-intro",
    "warm-1", "warm-2", "q1", "q2", "q3", "q4", "q5", "q6",
    "feedback",
]
QUESTION_IDS = PAGE_ORDER[4:12]
VOID_TAGS = {
    "area", "base", "br", "col", "embed", "hr", "img", "input",
    "link", "meta", "param", "source", "track", "wbr",
}


@dataclass
class Node:
    tag: str
    attrs: dict[str, str] = field(default_factory=dict)
    children: list[Node | str] = field(default_factory=list)


class TreeParser(HTMLParser):
    """A deliberately small DOM for the repository's authored HTML."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.root = Node("document")
        self.stack = [self.root]

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        node = Node(tag, {key: value or "" for key, value in attrs})
        self.stack[-1].children.append(node)
        if tag not in VOID_TAGS:
            self.stack.append(node)

    def handle_startendtag(self, tag: str,
                           attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)
        if tag not in VOID_TAGS:
            self.stack.pop()

    def handle_endtag(self, tag: str) -> None:
        for i in range(len(self.stack) - 1, 0, -1):
            if self.stack[i].tag == tag:
                del self.stack[i:]
                return

    def handle_data(self, data: str) -> None:
        self.stack[-1].children.append(data)


def parse_html(raw: str) -> Node:
    parser = TreeParser()
    parser.feed(raw)
    parser.close()
    return parser.root


def has_class(node: Node, name: str) -> bool:
    return name in node.attrs.get("class", "").split()


def walk(node: Node):
    for child in node.children:
        if isinstance(child, Node):
            yield child
            yield from walk(child)


def select(node: Node, *, tag: str | None = None,
           class_name: str | None = None,
           attr: str | None = None, value: str | None = None) -> list[Node]:
    found = []
    for candidate in walk(node):
        if tag is not None and candidate.tag != tag:
            continue
        if class_name is not None and not has_class(candidate, class_name):
            continue
        if attr is not None and attr not in candidate.attrs:
            continue
        if value is not None and candidate.attrs.get(attr) != value:
            continue
        found.append(candidate)
    return found


def one(node: Node, **selector) -> Node:
    found = select(node, **selector)
    if len(found) != 1:
        raise ValueError(f"expected one {selector}, found {len(found)}")
    return found[0]


def first(node: Node, **selector) -> Node | None:
    found = select(node, **selector)
    return found[0] if found else None


def node_text(node: Node, skip: set[int] | None = None) -> str:
    skip = skip or set()

    def collect(item: Node | str) -> str:
        if isinstance(item, str):
            return item
        if id(item) in skip:
            return ""
        if item.attrs.get("data-answer"):
            return item.attrs["data-answer"]
        if has_class(item, "build-zone") and item.attrs.get("data-a"):
            return item.attrs["data-a"]
        return "".join(collect(child) for child in item.children)

    return re.sub(r"\s+", " ", collect(node)).strip()


def semantic_text(node: Node) -> str:
    """Visible text independent of pretty-printed versus minified tag spacing."""
    parts = []

    def collect(item: Node | str) -> None:
        if isinstance(item, str):
            normalized = re.sub(r"\s+", " ", item).strip()
            if normalized:
                parts.append(normalized)
            return
        if item.attrs.get("data-answer"):
            parts.append(item.attrs["data-answer"])
            return
        if has_class(item, "build-zone") and item.attrs.get("data-a"):
            parts.append(item.attrs["data-a"])
            return
        for child in item.children:
            collect(child)

    collect(node)
    return " ".join(parts)


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def relative(path: pathlib.Path) -> str:
    return path.resolve().relative_to(REPO.resolve()).as_posix()


def validate_deck_shell(path: pathlib.Path, root: Node, *, allow_yomi: bool = False) -> None:
    """Keep projection generation coupled to the authored deck's static gates."""
    inline_styles = [node for node in walk(root)
                     if node.tag == "style" or "style" in node.attrs]
    if inline_styles:
        raise ValueError(f"{relative(path)}: inline CSS is not allowed")
    inline_scripts = [node for node in walk(root)
                      if node.tag == "script" and not node.attrs.get("src")
                      and node_text(node)]
    if inline_scripts:
        raise ValueError(f"{relative(path)}: inline JavaScript is not allowed")
    if not allow_yomi and any(has_class(node, "yomi") for node in walk(root)):
        raise ValueError(f"{relative(path)}: yomi is not allowed")

    sync_ids = [node.attrs["data-sync-id"] for node in walk(root)
                if node.attrs.get("data-sync-id")]
    if len(sync_ids) != len(set(sync_ids)):
        raise ValueError(f"{relative(path)}: duplicate data-sync-id values")

    legacy = [node.attrs.get("data-sync-id", "?") for node in walk(root)
              if node.tag == "span"
              and node.attrs.get("class") in {"slot", "answer-space"}
              and node.attrs.get("data-sync-id")]
    if legacy:
        raise ValueError(
            f"{relative(path)}: runtime-promoted control shells: {legacy[:3]}")

    for node in walk(root):
        for attr in ("href", "src"):
            ref = node.attrs.get(attr, "")
            if not ref or ref.startswith(("#", "data:", "http:", "https:",
                                          "mailto:", "tel:", "javascript:")):
                continue
            clean = urllib.parse.unquote(ref.split("#", 1)[0].split("?", 1)[0])
            if clean and not (path.parent / clean).resolve().exists():
                raise ValueError(
                    f"{relative(path)}: unresolved {attr} reference {ref}"
                )


def meta(root: Node) -> dict[str, str]:
    return {
        node.attrs["name"]: node.attrs.get("content", "")
        for node in select(root, tag="meta") if node.attrs.get("name")
    }


def lesson_pages(root: Node) -> list[Node]:
    phone = one(root, class_name="phone")
    return [child for child in phone.children
            if isinstance(child, Node) and child.attrs.get("data-page-id")]


def text_without(node: Node, excluded: list[Node | None]) -> str:
    return node_text(node, {id(item) for item in excluded if item is not None})


def add(entries: list[dict], page_id: str, field_name: str,
        language: str, text: str) -> None:
    if not text:
        raise ValueError(f"{page_id}/{field_name} is empty")
    entries.append({
        "pageId": page_id,
        "field": field_name,
        "language": language,
        "text": text,
    })


def extract_lesson(path: pathlib.Path, *, deep: bool, planned_title: str,
                   course_slug: str, theme: str, theme_number: int,
                   lesson_number: int) -> tuple[dict, dict[str, str]]:
    raw = path.read_text(encoding="utf-8")
    root = parse_html(raw)
    validate_deck_shell(path, root)
    metadata = meta(root)
    pages = lesson_pages(root)
    ids = [page.attrs["data-page-id"] for page in pages]
    if len(ids) != 13 or ids[0] != "lesson-goal" or \
            ids[1] not in ("model-story", "article") or \
            ids[2:] != PAGE_ORDER[2:]:
        raise ValueError(f"{relative(path)}: unexpected page order {ids}")
    if len(ids) != len(set(ids)):
        raise ValueError(f"{relative(path)}: duplicate page ids")

    lesson_id = path.parent.name
    if metadata.get("podo:lesson-id") != lesson_id:
        raise ValueError(f"{relative(path)}: lesson id does not match its directory")
    level = metadata.get("podo:level", "")
    expected_level = "고급" if course_slug.endswith("-advanced") else "중급"
    if level != expected_level:
        raise ValueError(f"{relative(path)}: expected level {expected_level}, got {level}")
    if metadata.get("google") != "notranslate":
        raise ValueError(f"{relative(path)}: missing google notranslate metadata")

    by_id = {page.attrs["data-page-id"]: page for page in pages}
    entries: list[dict] = []
    for language in ("ko", "en", "ja"):
        add(entries, "metadata", f"title.{language}", language,
            metadata.get(f"podo:title-{language}", ""))

    goal = by_id["lesson-goal"]
    add(entries, "lesson-goal", "act.ko", "ko", goal.attrs.get("data-act", ""))
    goal_subtitle = one(goal, class_name="section-subtitle")
    add(entries, "lesson-goal", "goal.ko", "ko",
        node_text(one(goal_subtitle, class_name="ko")))
    add(entries, "lesson-goal", "goal.ja", "ja",
        node_text(one(goal_subtitle, class_name="ja")))
    rows = select(goal, class_name="known-row")
    if len(rows) != 3:
        raise ValueError(f"{relative(path)}: expected three goal axes")
    for i, row in enumerate(rows, start=1):
        add(entries, "lesson-goal", f"axis.{i}.ko", "ko",
            node_text(one(row, class_name="k")))
        add(entries, "lesson-goal", f"axis.{i}.ja", "ja",
            node_text(one(row, class_name="j")))

    source_id = ids[1]
    source = by_id[source_id]
    add(entries, source_id, "source.title.ko", "ko",
        node_text(one(source, class_name="section-title")))
    source_subtitle = one(source, class_name="section-subtitle")
    for language in ("ko", "ja"):
        part = first(source_subtitle, class_name=language)
        if part is not None:
            add(entries, source_id, f"source.intro.{language}", language,
                node_text(part))
    source_note = first(source, class_name="tutor-note")
    if source_note is not None:
        add(entries, source_id, "source.tutorGuidance.ko", "ko",
            node_text(source_note))
    lines = select(source, class_name="sent")
    expected_lines = 7 if source_id == "article" else 5
    if len(lines) != expected_lines:
        raise ValueError(
            f"{relative(path)}: expected {expected_lines} {source_id} lines, "
            f"found {len(lines)}"
        )
    for line_number, line in enumerate(lines, start=1):
        add(entries, source_id, f"line.{line_number}.ko", "ko",
            node_text(one(line, class_name="s-ko")))
        add(entries, source_id, f"line.{line_number}.ja", "ja",
            node_text(one(line, class_name="s-ja")))
        words = select(line, class_name="s-w")
        keys = select(line, class_name="s-key")
        if len(words) != len(keys):
            raise ValueError(
                f"{relative(path)}: line {line_number} has "
                f"{len(keys)} highlighted terms and {len(words)} glosses"
            )
        for word_number, key in enumerate(keys, start=1):
            add(entries, source_id,
                f"line.{line_number}.highlight.{word_number}.ko", "ko",
                node_text(key))
        for word_number, word in enumerate(words, start=1):
            korean = one(word, tag="b")
            add(entries, source_id,
                f"line.{line_number}.vocabulary.{word_number}.ko", "ko",
                node_text(korean))
            add(entries, source_id,
                f"line.{line_number}.vocabulary.{word_number}.ja", "ja",
                text_without(word, [korean]))

    talk_intro = by_id["talk-intro"]
    add(entries, "talk-intro", "intro.ja", "ja",
        node_text(one(talk_intro, class_name="transition-copy")))

    for page_id in QUESTION_IDS:
        page = by_id[page_id]
        ask = one(page, class_name="ask")
        add(entries, page_id, "question.ko", "ko",
            node_text(one(ask, class_name="ko")))
        add(entries, page_id, "question.ja", "ja",
            node_text(one(ask, class_name="ja")))
        note = one(page, class_name="tutor-note")
        body = first(note, class_name="tn-body") or note
        cap = first(body, class_name="tn-cap")
        more = first(body, class_name="tn-more")
        guidance = text_without(body, [cap, more])
        if guidance:
            add(entries, page_id, "tutorGuidance.ko", "ko", guidance)
        followups = select(more, tag="li") if more is not None else []
        if len(followups) != 3:
            raise ValueError(f"{relative(path)}: {page_id} needs three follow-ups")
        for i, followup in enumerate(followups, start=1):
            add(entries, page_id, f"followUp.{i}.ko", "ko",
                node_text(followup))

    locator_keys = [(entry["pageId"], entry["field"]) for entry in entries]
    if len(locator_keys) != len(set(locator_keys)):
        raise ValueError(f"{relative(path)}: duplicate proofreading locators")

    signatures = {
        page_id: {
            "sha256": sha256(semantic_text(by_id[page_id])),
            "text": semantic_text(by_id[page_id]),
        }
        for page_id in ("lesson-style", "feedback")
    }
    record = {
        "formatVersion": FORMAT_VERSION,
        "source": relative(path),
        "sourceSha256": sha256(raw),
        "themeNumber": theme_number,
        "theme": theme,
        "course": course_slug,
        "lessonNumber": lesson_number,
        "lessonId": lesson_id,
        "plannedTitle": planned_title,
        "level": level,
        "deep": deep,
        "sourceKind": source_id,
        "entries": entries,
    }
    return record, signatures


def language_label(language: str) -> str:
    return {"ko": "KO", "ja": "JA", "en": "EN"}.get(language, language.upper())


def render_packet(theme_number: int, theme: str,
                  lessons: list[tuple[dict, dict]]) -> str:
    lines = [
        f"# 프리토킹 교정 패킷 {theme_number:02d} · {theme}",
        "",
        GENERATED,
        "",
        "HTML이 원본이다. 이 파일은 중요한 텍스트만 모은 검수용 투영이며 직접 고치지 않는다.",
        "수정 의견은 `source` + `pageId` + `field` + 현재 문장을 함께 적는다.",
        "",
        "생략: HTML/CSS/JS, 에셋, 페이저, 교정 입력칸, 공통 대화 스타일, 공통 피드백 화면.",
        "",
    ]
    for advanced, intermediate in lessons:
        marker = " · [깊게]" if advanced["deep"] else ""
        lines += [
            f"## {advanced['lessonNumber']:02d} · {advanced['plannedTitle']}{marker}",
            "",
        ]
        for record in (advanced, intermediate):
            lines += [
                f"### {record['level']}",
                "",
                f"- source: `{record['source']}`",
                f"- sha256: `{record['sourceSha256']}`",
                f"- source kind: `{record['sourceKind']}`",
                "",
            ]
            current_page = None
            for entry in record["entries"]:
                if entry["pageId"] != current_page:
                    if current_page is not None:
                        lines.append("")
                    current_page = entry["pageId"]
                    lines += [f"#### `{current_page}`", ""]
                lines.append(
                    f"- `{entry['field']}` · {language_label(entry['language'])}: "
                    f"{entry['text']}"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_boilerplate(groups: dict[str, dict[str, dict]]) -> str:
    lines = [
        "# 프리토킹 공통 화면 검수",
        "",
        GENERATED,
        "",
        "테마 패킷에서 반복을 줄이기 위해 뺀 `lesson-style`과 `feedback`의 고유한 텍스트다.",
        "같은 sha256은 공백을 정규화한 뒤 글자가 완전히 같다는 뜻이다.",
        "",
    ]
    for page_id in ("lesson-style", "feedback"):
        lines += [f"## `{page_id}`", ""]
        variants = groups[page_id]
        for i, (signature, info) in enumerate(sorted(variants.items()), start=1):
            lines += [
                f"### Variant {i}",
                "",
                f"- decks: {info['decks']}",
                f"- example: `{info['exampleSource']}`",
                f"- sha256: `{signature}`",
                "",
                f"> {info['text']}",
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def direct_children(node: Node, class_name: str) -> list[Node]:
    return [child for child in node.children
            if isinstance(child, Node) and has_class(child, class_name)]


def editorial_text(node: Node) -> str:
    """Visible prose without optional readings or decorative controls."""
    skipped = {
        id(candidate) for candidate in walk(node)
        if has_class(candidate, "yomi") or has_class(candidate, "correction-input")
    }
    return node_text(node, skipped)


def add_numbered(entries: list[dict], counters: dict[str, int], page_id: str,
                 role: str, language: str, value: str) -> None:
    value = value.strip()
    if not value:
        return
    key = f"{role}.{language}"
    counters[key] = counters.get(key, 0) + 1
    add(entries, page_id, f"{role}.{counters[key]}.{language}", language, value)


def generic_page_entries(page: Node) -> list[dict]:
    """Project stable editorial fields from any authored lesson page."""
    page_id = page.attrs["data-page-id"]
    entries: list[dict] = []
    counters: dict[str, int] = {}
    consumed: set[int] = set()

    if page.attrs.get("data-act"):
        add(entries, page_id, "act.ko", "ko", page.attrs["data-act"])

    title = first(page, class_name="section-title")
    if title is not None:
        title_ja = first(title, class_name="title-ja")
        add(entries, page_id, "title.ko", "ko", text_without(title, [title_ja]))
        if title_ja is not None:
            add(entries, page_id, "title.ja", "ja", editorial_text(title_ja))
        consumed.add(id(title))
        if title_ja is not None:
            consumed.add(id(title_ja))

    for subtitle in select(page, class_name="section-subtitle"):
        role = "patternMeaning" if has_class(subtitle, "pattern-meaning") else "tutorScript"
        for language in ("ko", "ja"):
            parts = direct_children(subtitle, language)
            for part in parts:
                add_numbered(entries, counters, page_id, role, language,
                             editorial_text(part))
                consumed.add(id(part))
                consumed.update(id(candidate) for candidate in walk(part))

    for note in select(page, class_name="tutor-note"):
        add_numbered(entries, counters, page_id, "tutorNote", "ko",
                     editorial_text(note))
        consumed.add(id(note))
        consumed.update(id(candidate) for candidate in walk(note))

    for block_number, block in enumerate(select(page, class_name="task-block"), start=1):
        answer = first(block, class_name="answer-space")
        prompt = first(block, class_name="answer-label")
        if prompt is not None:
            prompt_text = editorial_text(prompt)
            if prompt_text:
                add(entries, page_id, f"task.{block_number}.prompt.ja", "ja",
                    prompt_text)
            consumed.add(id(prompt))
            consumed.update(id(candidate) for candidate in walk(prompt))
        if answer is not None:
            answer_text = editorial_text(answer)
            if answer_text:
                add(entries, page_id, f"task.{block_number}.answer.ko", "ko",
                    answer_text)
            consumed.add(id(answer))
            consumed.update(id(candidate) for candidate in walk(answer))
        for choice_number, choice in enumerate(select(block, class_name="choice"), start=1):
            choice_text = editorial_text(choice)
            if choice_text:
                add(entries, page_id,
                    f"task.{block_number}.choice.{choice_number}.ko", "ko",
                    choice_text)
            consumed.add(id(choice))
            consumed.update(id(candidate) for candidate in walk(choice))

    # Remaining paired-language spans include questions, dialogue, examples,
    # outcome rows and translations that are not part of a task block.
    language_classes = {
        "ko": "ko", "ja": "ja", "s-ko": "ko", "s-ja": "ja",
        "k": "ko", "j": "ja", "korean": "ko", "english": "en",
        "title-ja": "ja", "translation": "ja", "transition-copy": "ja",
        "answer-label": "ja", "mean": "ja", "yomi-line": "ja",
        "kana-eq": "ja", "opt": "ko", "read-chip": "ko",
    }
    for candidate in walk(page):
        if id(candidate) in consumed:
            continue
        classes = candidate.attrs.get("class", "").split()
        matched = next((name for name in classes if name in language_classes), None)
        if matched is None:
            continue
        # A container whose descendant carries the same language is context,
        # not a second editable field.
        if any(
            any(name in language_classes and language_classes[name] == language_classes[matched]
                for name in child.attrs.get("class", "").split())
            for child in walk(candidate)
        ):
            continue
        role = {
            "title-ja": "title", "translation": "translation",
            "transition-copy": "transition", "s-ko": "sentence",
            "s-ja": "sentence", "k": "outcome", "j": "outcome",
        }.get(matched, "text")
        add_numbered(entries, counters, page_id, role,
                     language_classes[matched], editorial_text(candidate))
        consumed.add(id(candidate))

    keys = [(entry["pageId"], entry["field"]) for entry in entries]
    if len(keys) != len(set(keys)):
        raise ValueError(f"duplicate generic locators on {page_id}")
    return entries


def extract_generic_lesson(path: pathlib.Path) -> dict:
    raw = path.read_text(encoding="utf-8")
    root = parse_html(raw)
    validate_deck_shell(path, root, allow_yomi=True)
    metadata = meta(root)
    pages = lesson_pages(root)
    page_ids = [page.attrs["data-page-id"] for page in pages]
    if not pages or len(page_ids) != len(set(page_ids)):
        raise ValueError(f"{relative(path)}: missing or duplicate page ids")
    if metadata.get("google") != "notranslate":
        raise ValueError(f"{relative(path)}: missing google notranslate metadata")
    if metadata.get("podo:lesson-id") != path.parent.name:
        raise ValueError(f"{relative(path)}: lesson id does not match its directory")
    level = metadata.get("podo:level", "")
    if level in {"중급", "중고급", "고급"} and any(
            has_class(node, "yomi") for node in walk(root)):
        raise ValueError(f"{relative(path)}: yomi is not allowed at level {level}")

    entries = []
    for language in ("ko", "en", "ja"):
        add(entries, "metadata", f"title.{language}", language,
            metadata.get(f"podo:title-{language}", ""))
    page_contexts = []
    for page in pages:
        entries.extend(generic_page_entries(page))
        page_contexts.append({
            "pageId": page.attrs["data-page-id"],
            "text": semantic_text(page),
        })
    keys = [(entry["pageId"], entry["field"]) for entry in entries]
    if len(keys) != len(set(keys)):
        raise ValueError(f"{relative(path)}: duplicate proofreading locators")

    course = path.parents[2].name
    lesson_id = path.parent.name
    number_match = re.match(r"([0-9]+)-", lesson_id)
    if not number_match:
        raise ValueError(f"{relative(path)}: lesson directory has no numeric prefix")
    return {
        "formatVersion": FORMAT_VERSION,
        "source": relative(path),
        "sourceSha256": sha256(raw),
        "track": path.parents[4].name,
        "course": course,
        "lessonNumber": int(number_match.group(1)),
        "lessonId": lesson_id,
        "level": level,
        "pageContexts": page_contexts,
        "entries": entries,
    }


def render_generic_packet(track: str, course: str, records: list[dict]) -> str:
    lines = [
        f"# {track} · {course} 교정 패킷",
        "",
        GENERATED,
        "",
        "HTML이 원본이다. 이 파일은 언어·지시·활동 의미를 검수하기 위한 읽기 전용 투영이다.",
        "수정 의견은 `source` + `pageId` + `field` + 현재 문장을 정확히 인용한다.",
        "",
    ]
    for record in records:
        lines += [
            f"## {record['lessonNumber']:02d} · {record['lessonId']}", "",
            f"- source: `{record['source']}`",
            f"- sha256: `{record['sourceSha256']}`",
            f"- level: {record['level']}", "",
        ]
        contexts = {item["pageId"]: item["text"] for item in record["pageContexts"]}
        current_page = None
        for entry in record["entries"]:
            if entry["pageId"] != current_page:
                current_page = entry["pageId"]
                lines += [f"### `{current_page}`", ""]
                if current_page in contexts:
                    lines += [f"> {contexts[current_page]}", ""]
            lines.append(
                f"- `{entry['field']}` · {language_label(entry['language'])}: "
                f"{entry['text']}"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_generic_outputs(track: pathlib.Path) -> tuple[dict[pathlib.Path, str], list[dict]]:
    course_records: OrderedDict[str, list[dict]] = OrderedDict()
    for path in sorted(track.glob("courses/*/lessons/*/lesson.html")):
        record = extract_generic_lesson(path)
        course_records.setdefault(record["course"], []).append(record)
    if not course_records:
        raise ValueError(f"{relative(track)} has no authored lesson decks")

    outputs: dict[pathlib.Path, str] = {}
    records = []
    packet_specs = []
    for number, (course, items) in enumerate(course_records.items(), start=1):
        items.sort(key=lambda item: (item["lessonNumber"], item["lessonId"]))
        records.extend(items)
        packet_path = pathlib.Path("packets") / f"{number:02d}-{course}.md"
        outputs[packet_path] = render_generic_packet(track.name, course, items)
        packet_specs.append({
            "course": course,
            "file": packet_path.as_posix(),
            "decks": len(items),
            "sourceSetSha256": sha256("\n".join(
                item["source"] + "\0" + item["sourceSha256"] for item in items
            )),
        })
    outputs[pathlib.Path("lessons.jsonl")] = "".join(
        json.dumps(record, ensure_ascii=False, sort_keys=True,
                   separators=(",", ":")) + "\n" for record in records
    )
    outputs[pathlib.Path("manifest.json")] = json.dumps({
        "formatVersion": FORMAT_VERSION,
        "generator": GENERATOR,
        "htmlIsSourceOfTruth": True,
        "track": relative(track),
        "counts": {
            "courses": len(course_records),
            "decks": len(records),
            "entries": sum(len(record["entries"]) for record in records),
        },
        "packets": packet_specs,
    }, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    outputs[pathlib.Path("README.md")] = "\n".join([
        f"# {track.name} 교정 패킷", "", GENERATED, "",
        "[`../../PROOFREADING-WORKFLOW.md`](../../PROOFREADING-WORKFLOW.md)의 완전 검수 절차를 따른다.",
        "", "- `packets/`: 코스 단위 의미 검수용 Markdown",
        "- `lessons.jsonl`: exact source/page/field locator와 페이지 문맥",
        "- `manifest.json`: 원본 해시와 패킷 구성", "",
        "수정은 원본 `lesson.html`에만 적용하고 이 투영을 다시 생성한다.", "",
    ])
    return outputs, records


def build_outputs(track: pathlib.Path) -> tuple[dict[pathlib.Path, str], list[dict]]:
    if track.name in GENERIC_TRACKS:
        return build_generic_outputs(track)
    if track.name != "4-freetalking":
        raise ValueError(
            f"unsupported track {track.name}; release packets cover tracks 1-4"
        )
    parsed = []
    for course in track_parsers.parse_freetalking(track):
        theme_title = course["title"]["ko"]
        composed = plan_courses.compose(course, plan_courses.TRACKS[track.name])
        composed["proofreadingThemeTitle"] = theme_title
        parsed.append(composed)
    themes: OrderedDict[str, dict] = OrderedDict()
    for course in parsed:
        key = course["pairKey"]
        theme = themes.setdefault(key, {
            "title": course["proofreadingThemeTitle"],
            "levels": {},
        })
        theme["levels"][course["level"]] = course

    records: list[dict] = []
    packet_specs: list[dict] = []
    signature_groups: dict[str, dict[str, dict]] = {
        "lesson-style": {}, "feedback": {},
    }
    outputs: dict[pathlib.Path, str] = {}

    for theme_number, (key, theme) in enumerate(themes.items(), start=1):
        if set(theme["levels"]) != {"중급", "고급"}:
            raise ValueError(f"theme {key} does not have both levels")
        advanced_course = theme["levels"]["고급"]
        intermediate_course = theme["levels"]["중급"]
        if len(advanced_course["lessons"]) != len(intermediate_course["lessons"]):
            raise ValueError(f"theme {key} has mismatched level lengths")
        packet_lessons = []
        packet_sources = []
        for advanced_plan, intermediate_plan in zip(
                advanced_course["lessons"], intermediate_course["lessons"]):
            if advanced_plan["no"] != intermediate_plan["no"]:
                raise ValueError(f"theme {key} has mismatched lesson numbers")
            planned_pair = []
            for course, lesson in (
                    (advanced_course, advanced_plan),
                    (intermediate_course, intermediate_plan)):
                lesson_root = track / "courses" / course["slug"] / "lessons"
                matches = sorted(lesson_root.glob(f"{lesson['no']:02d}-*/lesson.html"))
                if len(matches) > 1:
                    raise ValueError(
                        f"{course['slug']} lesson {lesson['no']}: "
                        f"expected at most one deck, found {len(matches)}"
                    )
                planned_pair.append((course, lesson, matches))
            written_counts = [len(item[2]) for item in planned_pair]
            if written_counts == [0, 0]:
                continue
            if written_counts != [1, 1]:
                raise ValueError(
                    f"theme {key} lesson {advanced_plan['no']}: "
                    "advanced and intermediate must be authored together"
                )
            pair = []
            for course, lesson, matches in planned_pair:
                record, signatures = extract_lesson(
                    matches[0], deep=lesson.get("deep", False),
                    planned_title=lesson["title"], course_slug=course["slug"],
                    theme=theme["title"], theme_number=theme_number,
                    lesson_number=lesson["no"],
                )
                pair.append(record)
                records.append(record)
                packet_sources.append({
                    "source": record["source"],
                    "sourceSha256": record["sourceSha256"],
                })
                for page_id, signature_data in signatures.items():
                    signature = signature_data["sha256"]
                    group = signature_groups[page_id].setdefault(signature, {
                        "decks": 0,
                        "text": signature_data["text"],
                        "exampleSource": record["source"],
                    })
                    group["decks"] += 1
            packet_lessons.append((pair[0], pair[1]))

        packet_path = pathlib.Path("packets") / f"{theme_number:02d}-{key}.md"
        outputs[packet_path] = render_packet(
            theme_number, theme["title"], packet_lessons
        )
        packet_specs.append({
            "themeNumber": theme_number,
            "theme": theme["title"],
            "file": packet_path.as_posix(),
            "lessonPairs": len(packet_lessons),
            "decks": len(packet_sources),
            "sourceSetSha256": sha256("\n".join(
                item["source"] + "\0" + item["sourceSha256"]
                for item in packet_sources
            )),
        })

    records.sort(key=lambda record: (
        record["themeNumber"], record["lessonNumber"],
        0 if record["level"] == "고급" else 1,
    ))
    jsonl = "".join(
        json.dumps(record, ensure_ascii=False, sort_keys=True,
                   separators=(",", ":")) + "\n"
        for record in records
    )
    outputs[pathlib.Path("lessons.jsonl")] = jsonl
    outputs[pathlib.Path("boilerplate.md")] = render_boilerplate(signature_groups)
    manifest = {
        "formatVersion": FORMAT_VERSION,
        "generator": GENERATOR,
        "htmlIsSourceOfTruth": True,
        "track": relative(track),
        "counts": {
            "themes": len(themes),
            "lessonPairs": len(records) // 2,
            "decks": len(records),
            "entries": sum(len(record["entries"]) for record in records),
        },
        "omittedBoilerplateSignatures": {
            page_id: [
                {
                    "sha256": signature,
                    "decks": info["decks"],
                    "exampleSource": info["exampleSource"],
                }
                for signature, info in sorted(groups.items())
            ]
            for page_id, groups in signature_groups.items()
        },
        "packets": packet_specs,
    }
    outputs[pathlib.Path("manifest.json")] = (
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )
    outputs[pathlib.Path("README.md")] = "\n".join([
        "# 프리토킹 교정 패킷",
        "",
        GENERATED,
        "",
        "전체 검수 순서와 이슈 형식은 [`../../PROOFREADING-WORKFLOW.md`](../../PROOFREADING-WORKFLOW.md)를 따른다.",
        "",
        "- `packets/`: 테마별 고급·중급 짝 검수용 Markdown",
        "- `lessons.jsonl`: 정확한 `source` / `pageId` / `field` 로 찾는 기계용 텍스트",
        "- `boilerplate.md`: 테마 패킷에서 생략한 공통 화면의 고유 텍스트",
        "- `manifest.json`: 원본 HTML 해시, 개수, 생략된 공통 화면의 서명",
        "",
        "수정은 이 폴더가 아니라 원본 `lesson.html`에 반영한 뒤 다시 생성한다.",
        "",
    ])
    return outputs, records


def generated_stale_files(output: pathlib.Path,
                          expected: set[pathlib.Path]) -> list[pathlib.Path]:
    stale = []
    if not output.exists():
        return stale
    for path in output.rglob("*.md"):
        if path not in expected and GENERATED in path.read_text(encoding="utf-8"):
            stale.append(path)
    return stale


def write_outputs(output: pathlib.Path, outputs: dict[pathlib.Path, str]) -> None:
    expected = {output / path for path in outputs}
    stale = generated_stale_files(output, expected)
    if stale:
        joined = "\n  ".join(str(path) for path in stale)
        raise ValueError(
            "generated packets are no longer expected; review and remove them explicitly:\n  "
            + joined
        )
    for relative_path, content in outputs.items():
        path = output / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_outputs(output: pathlib.Path,
                  outputs: dict[pathlib.Path, str]) -> list[str]:
    errors = []
    expected = {output / path for path in outputs}
    for relative_path, content in outputs.items():
        path = output / relative_path
        if not path.exists():
            errors.append(f"missing {path}")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"stale {path}")
    errors.extend(f"unexpected generated file {path}"
                  for path in generated_stale_files(output, expected))
    return errors


def validate_superseding_issue(path: pathlib.Path, reference: str,
                               locator: tuple[str, str, str],
                               previous_suggestion: str,
                               applied_text: str) -> str | None:
    """Validate an explicit later-round replacement for an applied suggestion."""
    match = re.fullmatch(r"([^:]+\.jsonl):([1-9][0-9]*)", reference)
    if not match:
        return "supersededBy must be a relative .jsonl path plus a line number"
    target_path = (path.parent / match.group(1)).resolve()
    try:
        lines = target_path.read_text(encoding="utf-8").splitlines()
        target = json.loads(lines[int(match.group(2)) - 1])
    except (OSError, IndexError, json.JSONDecodeError) as exc:
        return f"cannot read superseding issue {reference} ({exc})"
    target_locator = (target.get("source"), target.get("pageId"), target.get("field"))
    if target_locator != locator:
        return f"superseding issue {reference} cites a different locator"
    if target.get("current") != previous_suggestion:
        return f"superseding issue {reference} does not continue this edit chain"
    if target.get("suggested") != applied_text:
        return f"superseding issue {reference} is not applied"
    return None


def validate_issues(path: pathlib.Path, records: list[dict], *, applied: bool = False) -> int:
    index = {
        (record["source"], entry["pageId"], entry["field"]): entry["text"]
        for record in records for entry in record["entries"]
    }
    source_hashes = {
        record["source"]: record["sourceSha256"] for record in records
    }
    errors = []
    count = 0
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        count += 1
        try:
            issue = json.loads(raw)
        except json.JSONDecodeError as exc:
            errors.append(f"line {line_number}: invalid JSON ({exc.msg})")
            continue
        required = ("source", "sourceSha256", "pageId", "field", "current",
                    "suggested", "category", "severity", "reason")
        missing = [key for key in required if not issue.get(key)]
        if missing:
            errors.append(f"line {line_number}: missing {', '.join(missing)}")
            continue
        locator = (issue["source"], issue["pageId"], issue["field"])
        if issue["source"] not in source_hashes:
            errors.append(f"line {line_number}: unknown source {issue['source']}")
        elif not applied and issue["sourceSha256"] != source_hashes[issue["source"]]:
            errors.append(f"line {line_number}: source hash is stale for {issue['source']}")
        elif applied and not re.fullmatch(r"[0-9a-f]{64}", issue["sourceSha256"]):
            errors.append(f"line {line_number}: source hash is not a 64-character sha256")
        if locator not in index:
            errors.append(f"line {line_number}: unknown locator {locator}")
        elif applied and issue["suggested"] != index[locator]:
            reference = issue.get("supersededBy")
            if not reference:
                errors.append(f"line {line_number}: suggestion is not applied for {locator}")
            else:
                error = validate_superseding_issue(
                    path, reference, locator, issue["suggested"], index[locator]
                )
                if error:
                    errors.append(f"line {line_number}: {error}")
        elif not applied and issue["current"] != index[locator]:
            errors.append(f"line {line_number}: current text is stale for {locator}")
        if issue["current"] == issue["suggested"]:
            errors.append(f"line {line_number}: suggestion does not change the text")
        if issue["severity"] not in ("error", "warning", "suggestion"):
            errors.append(
                f"line {line_number}: severity must be error, warning or suggestion"
            )
    if errors:
        raise ValueError("invalid proofreading issues:\n  " + "\n  ".join(errors))
    return count


def refresh_issue_hashes(path: pathlib.Path, records: list[dict]) -> int:
    """Rebase hashes only when all issue locators still match original text."""
    index = {
        (record["source"], entry["pageId"], entry["field"]): entry["text"]
        for record in records for entry in record["entries"]
    }
    source_hashes = {
        record["source"]: record["sourceSha256"] for record in records
    }
    parsed = []
    errors = []
    required = ("source", "sourceSha256", "pageId", "field", "current",
                "suggested", "category", "severity", "reason")
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        try:
            issue = json.loads(raw)
        except json.JSONDecodeError as exc:
            errors.append(f"line {line_number}: invalid JSON ({exc.msg})")
            continue
        missing = [key for key in required if not issue.get(key)]
        if missing:
            errors.append(f"line {line_number}: missing {', '.join(missing)}")
            continue
        source = issue["source"]
        locator = (source, issue["pageId"], issue["field"])
        if source not in source_hashes:
            errors.append(f"line {line_number}: unknown source {source}")
        elif locator not in index:
            errors.append(f"line {line_number}: unknown locator {locator}")
        elif issue["current"] != index[locator]:
            errors.append(f"line {line_number}: current text is stale for {locator}")
        if issue["current"] == issue["suggested"]:
            errors.append(f"line {line_number}: suggestion does not change the text")
        if issue["severity"] not in ("error", "warning", "suggestion"):
            errors.append(
                f"line {line_number}: severity must be error, warning or suggestion"
            )
        parsed.append(issue)
    if errors:
        raise ValueError(
            "cannot refresh proofreading issue hashes:\n  " + "\n  ".join(errors)
        )
    for issue in parsed:
        issue["sourceSha256"] = source_hashes[issue["source"]]
    path.write_text("".join(
        json.dumps(issue, ensure_ascii=False, separators=(",", ":")) + "\n"
        for issue in parsed
    ), encoding="utf-8")
    return len(parsed)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("track", type=pathlib.Path,
                        help="one release track under sandbox/drafts/kr/tracks (1 through 4)")
    parser.add_argument("--output", type=pathlib.Path,
                        help="default: korean/proofreading/<track-name>")
    parser.add_argument("--check", action="store_true",
                        help="fail if generated packets differ from the HTML")
    parser.add_argument("--validate-issues", type=pathlib.Path,
                        help="validate a reviewer issue JSONL against current HTML")
    parser.add_argument("--verify-applied", type=pathlib.Path,
                        help="verify every issue suggestion is present in current HTML")
    parser.add_argument("--refresh-issue-hashes", type=pathlib.Path,
                        help="refresh hashes only if every cited current field still matches")
    args = parser.parse_args()

    issue_modes = [args.validate_issues, args.verify_applied, args.refresh_issue_hashes]
    if sum(mode is not None for mode in issue_modes) > 1:
        parser.error("issue validation, verification, and hash refresh are mutually exclusive")

    track = args.track.resolve()
    output = (args.output or (KOREAN / "proofreading" / track.name)).resolve()
    try:
        outputs, records = build_outputs(track)
        if args.validate_issues:
            count = validate_issues(args.validate_issues, records)
            print(f"✓ {count} proofreading issue(s) match the current HTML")
        if args.verify_applied:
            count = validate_issues(args.verify_applied, records, applied=True)
            print(f"✓ {count} proofreading issue suggestion(s) are applied")
        if args.refresh_issue_hashes:
            count = refresh_issue_hashes(args.refresh_issue_hashes, records)
            print(f"✓ refreshed source hashes for {count} proofreading issue(s)")
        if args.check:
            errors = check_outputs(output, outputs)
            if errors:
                raise ValueError("proofreading packets are not current:\n  " + "\n  ".join(errors))
            packet_count = sum(path.parts[0] == "packets" for path in outputs)
            print(f"✓ {len(records)} decks · {packet_count} packets are current")
        elif not any(issue_modes):
            write_outputs(output, outputs)
            packet_count = sum(path.parts[0] == "packets" for path in outputs)
            print(f"→ {output}")
            kind = "paired-theme" if track.name == "4-freetalking" else "course"
            print(f"  {len(records)} decks · {packet_count} {kind} packets")
    except (OSError, ValueError, track_parsers.ParseError) as exc:
        print(f"✗ {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
