#!/usr/bin/env python3
"""Build small, course-aware lesson briefs from every track's TOC.

    python3 tools/authoring/kr/build_lesson_briefs.py sandbox/drafts/kr/tracks/3-contextual-korean
    python3 tools/authoring/kr/build_lesson_briefs.py --all

Tracks whose lesson numbers restart in each course cannot use a flat
`toc/lesson-001.md`: fourteen different contextual lessons are numbered 1.
Their briefs therefore live at:

    tracks/<track>/toc/<course-code>/lesson-NNN.md

`course-code` is the deployable course slug produced by plan_courses.py, so the
brief, course plan and lesson scaffold all use one unambiguous identifier.

Core patterns keeps its richer legacy sharder and flat, globally numbered
briefs. This command delegates that track to shard_toc.py so authors still have
one entry point for all five curricula.
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

import plan_courses
import track_parsers


HERE = pathlib.Path(__file__).resolve().parents[3] / "sandbox/drafts/kr"
GENERATED = "Generated by `tools/authoring/kr/build_lesson_briefs.py` — do not edit this file."


def _value(label: str, value: str | None) -> list[str]:
    return [f"- **{label}:** {value}"] if value else []


def _lesson_label(lesson: dict) -> str:
    return lesson["title"] + (" [깊게]" if lesson.get("deep") else "")


def render_brief(track: pathlib.Path, course: dict, lesson: dict,
                 prior: dict | None, following: dict | None) -> str:
    number = lesson["no"]
    title = lesson["title"]
    lines = [
        f"# {course['title']['ko']} · {number} · {title}",
        "",
        GENERATED,
        "원본은 `table-of-contents.md`다. 내용이 틀리면 이 파일이 아니라 원본과 파서를 고친다.",
        "",
        "## Course code",
        "",
        f"- **Track:** `{track.name}`",
        f"- **Course:** `{course['slug']}`",
        f"- **Level:** {course['level']}",
        f"- **Lesson:** `{number:03d}` of `{len(course['lessons']):03d}`",
        "",
        "이 네 값은 함께 움직인다. 특히 레슨 번호가 코스마다 다시 시작하는 트랙에서는",
        "`Course` 없이 `Lesson`만으로 덱을 고르거나 생성하지 않는다.",
        "",
        "## Course brief",
        "",
    ]
    lines += _value("Course outcome", course.get("note"))
    lines += _value("Session format", course.get("sessionFormat"))
    lines += _value("Work", course.get("work"))
    lines += _value("Cast", course.get("cast"))
    for note in course.get("story", []):
        lines.append(f"> {note}")

    if track.name == "4-freetalking":
        lines += ["", "## Level version", ""]
        sibling = course.get("pairedCourse")
        if course["level"] == "고급":
            lines += [
                "- **Authoring order:** Write this Advanced lesson first.",
                "- Use the strongest natural article or model story and the most interesting question ladder for the topic.",
                f"- **Intermediate sibling:** `{sibling}` · lesson `{number:03d}`.",
            ]
        else:
            lines += [
                f"- **Adapt from:** `{sibling}` · lesson `{number:03d}`.",
                "- Keep the topic, page order, question intent and conversation arc the same.",
                "- Simplify the article or model story first. Keep already-accessible questions unchanged; rewrite only questions whose language is too difficult.",
                "- Lower vocabulary and sentence complexity, not the intellectual interest of the conversation.",
            ]

    lines += ["", "## Lesson brief", ""]
    lines += _value("Title", title)
    lines += _value("Scene", lesson.get("scene"))
    lines += _value("Can do", lesson.get("canDo"))
    if lesson.get("deep"):
        lines += _value("Sensitive topic", "[깊게] — 관계가 생긴 뒤에 사용")

    dialogues = lesson.get("dialogues", [])
    if dialogues:
        lines += ["", "## Required dramatic exchanges", ""]
        for i, exchange in enumerate(dialogues, start=1):
            lines += [f"### Exchange {i}", "",
                      f"- **Learner line:** {exchange['line']}",
                      f"- **Pattern:** `{exchange['form']}`"]
            lines += _value("Core reference", exchange.get("reference"))
            lines += _value("Partner reaction", exchange.get("reaction"))
            lines.append("")
    elif lesson.get("patterns"):
        lines += ["", "## Required teaching content", ""]
        lines.extend(f"- `{pattern}`" for pattern in lesson["patterns"])

    extra_fields = [
        ("Expressions", lesson.get("expressions")),
        ("Grammar / nuance", lesson.get("grammar")),
        ("Receptive only", lesson.get("understanding")),
        ("Teach as a chunk", lesson.get("chunk")),
        ("Author note", lesson.get("memo")),
    ]
    present = [(label, value) for label, value in extra_fields if value]
    if present:
        lines += ["", "## Supporting content", ""]
        for label, value in present:
            lines.append(f"- **{label}:** {value}")

    lines += ["", "## Continuity", ""]
    lines.append(
        f"- **Previous:** {prior['no']} · {_lesson_label(prior)}" if prior
        else "- **Previous:** course opening"
    )
    lines.append(
        f"- **Next:** {following['no']} · {_lesson_label(following)}" if following
        else "- **Next:** course ending"
    )
    if track.name == "3-contextual-korean":
        lines += [
            "- Preserve the course's cast, relationship state and chronology; this is an episode, not a topic sample.",
            "- End on the next-episode teaser. Put the native tip immediately before it.",
            "- If a scene must be split, split only at a dramatic beat and mirror the same boundaries in the replay.",
        ]

    lines += [
        "",
        "## Authoring inputs — read in this order",
        "",
        "1. `korean/LESSON-CREATION-WORKFLOW.md`",
        f"2. `sandbox/drafts/kr/tracks/{track.name}/lesson-blueprint.md`",
        "3. This brief",
        "4. The complete canonical trial deck named by the blueprint",
        "5. `korean/AUTHORING.md` for existing component markup",
        "",
        "Do not invent a second grammar sequence, a new shared component, or a disconnected bonus scene inside a lesson-writing assignment.",
        "",
    ]
    return "\n".join(lines)


def build_track(track: pathlib.Path) -> tuple[int, int]:
    if track.name == "2-core-patterns":
        subprocess.run(
            [sys.executable, str(pathlib.Path(__file__).resolve().parent / "shard_toc.py"), str(track)],
            check=True,
        )
        units = track_parsers.parse_core(track)
        return len(plan_courses.pack_core(units)), sum(len(unit["lessons"]) for unit in units)

    parser = track_parsers.PARSERS.get(track.name)
    cfg = plan_courses.TRACKS.get(track.name)
    if parser is None or cfg is None:
        raise SystemExit(f"no brief builder for track '{track.name}'")

    courses = [plan_courses.compose(course, cfg) for course in parser(track)]
    pairs = {(course.get("pairKey"), course["level"]): course["slug"]
             for course in courses if course.get("pairKey")}
    for course in courses:
        if course.get("pairKey"):
            sibling_level = "고급" if course["level"] == "중급" else "중급"
            course["pairedCourse"] = pairs[(course["pairKey"], sibling_level)]
    toc_dir = track / "toc"
    toc_dir.mkdir(exist_ok=True)
    expected: set[pathlib.Path] = set()
    index = [
        f"# {track.name} lesson briefs",
        "",
        GENERATED,
        "",
        "Lesson numbers may restart per course. Always identify a lesson by both course code and number.",
        "",
    ]

    for course in courses:
        course_dir = toc_dir / course["slug"]
        course_dir.mkdir(exist_ok=True)
        index += [f"## `{course['slug']}` · {course['title']['ko']}", ""]
        lessons = course["lessons"]
        for i, lesson in enumerate(lessons):
            path = course_dir / f"lesson-{lesson['no']:03d}.md"
            path.write_text(render_brief(
                track, course, lesson,
                lessons[i - 1] if i else None,
                lessons[i + 1] if i + 1 < len(lessons) else None,
            ), encoding="utf-8")
            expected.add(path)
            index.append(
                f"- [`{lesson['no']:03d}`]({course['slug']}/{path.name}) "
                f"{_lesson_label(lesson)}"
            )
        index.append("")

    index_path = toc_dir / "index.md"
    index_path.write_text("\n".join(index), encoding="utf-8")
    expected.add(index_path)

    stale = [path for path in toc_dir.rglob("*.md")
             if path not in expected and GENERATED in path.read_text(encoding="utf-8")]
    if stale:
        joined = "\n  ".join(str(path) for path in stale)
        raise SystemExit(
            "generated briefs no longer present in the TOC; review and remove them explicitly:\n  "
            + joined
        )

    count = sum(len(course["lessons"]) for course in courses)
    print(f"{count} course-scoped briefs from {len(courses)} courses -> {toc_dir}")
    return len(courses), count


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("track", nargs="?", help="e.g. sandbox/drafts/kr/tracks/3-contextual-korean")
    ap.add_argument("--all", action="store_true", help="build briefs for all five tracks")
    args = ap.parse_args()
    if args.all:
        targets = [HERE / "tracks" / name for name in sorted(plan_courses.TRACKS)]
    elif args.track:
        targets = [pathlib.Path(args.track)]
    else:
        return ap.error("give a track path or --all")

    courses = lessons = 0
    for track in targets:
        course_count, lesson_count = build_track(track)
        courses += course_count
        lessons += lesson_count
    print(f"{courses} course(s), {lessons} lesson brief(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
