#!/usr/bin/env python3
"""
Import the trial decks from the authoring tree into courses/kr/hangul-trial-test.

Upstream these four decks share one `runtime/`. Input controls already exist in
the source HTML, so this importer preserves them and performs two packaging
transforms:

  1. flatten refs   — `../../runtime/js/x.js` → `x.js`, `../assets/**/y` → `y`,
     and the two remote avatars become bundled local files.
  2. bundle         — `lesson-card.css`, `trial.css` and every referenced script
     are copied from the synced `shared/` snapshot next to the deck; images are
     copied from their owning source. `build.py` merges the two sheets in link
     order into the single `lesson.css` grape renames per slot.

The importer rejects runtime-promoted control shells. Lemonboard validates the
source without running scripts, so authoring HTML, packaged HTML and the live DOM
must all contain the same real controls. `podo-curriculum-public/runtime` is the
authoring source of truth; `shared/` is the exact release snapshot synced from it.

**This script owns `lessons/` completely** — it clears the directory each run so a
deck retired upstream disappears here, which means it writes `lesson.yaml` too.
Add a deck by adding a row to DECKS below.

Run `sync-from-authoring.py` first. The importer deliberately bundles runtime
files from `shared/`, not another implementation.

    python3 tools/import-trial-decks.py [--upstream PATH]
"""
from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import sys

import upstream

REPO = upstream.REPO
COURSE = REPO / "courses" / "kr" / "hangul-trial-test"

# Bundled rather than fetched: a deck has to survive a locked-down classroom
# network, and these two are the only images the source leaves on a remote host.
AVATARS = {
    "https://respeak-lemonade.s3.ap-northeast-2.amazonaws.com/test/hana-avatar.jpg":
        "hana-avatar.jpg",
    "https://respeak-lemonade.s3.ap-northeast-2.amazonaws.com/test/haruka-avatar.jpg":
        "haruka-avatar.jpg",
}

# source deck -> lesson directory, CLASS_WEEK, and the three-language title.
DECKS = [
    ("trial-1-hangul-short.html", "01-trial-hangul", 1,
     {"ko": "체험 · 초입문 한글",
      "en": "Trial · Hangul from zero",
      "ja": "体験レッスン 超入門"}),
    ("trial-2-patterns-short.html", "02-trial-self-intro", 2,
     {"ko": "체험 · 초급 자기소개",
      "en": "Trial · Introducing yourself",
      "ja": "体験レッスン 初級 · 自己紹介"}),
    ("trial-3-contextual-short.html", "03-trial-first-meeting", 3,
     {"ko": "체험 · 중급 우리, 어디서 본 적 있죠?",
      "en": "Trial · Haven't we met somewhere?",
      "ja": "体験レッスン 中級 · 第1話 どこかで会いましたよね？"}),
    ("trial-4-freetalking-short.html", "04-trial-free-talking", 4,
     {"ko": "체험 · 고급 프리토킹",
      "en": "Trial · Free talking",
      "ja": "体験レッスン 上級 · フリートーキング"}),
]

LESSON_YAML = """\
apiVersion: podo.curriculum/v1
kind: Lesson
metadata:
  slug: {slug}

spec:
  week: {week}

  title:
    ko: {ko}
    en: {en}
    ja: {ja}

  decks:
    lecture:  {{ entry: lecture/index.html }}
    prestudy: {{ entry: prestudy/index.html }}

  # 덱을 옮겨 온 것이라 teaches/outcome 은 비워 둔다 — 원본 기획 문서가 아니라
  # 덱에서 읽어낸 것을 적으면 리뷰가 실제 덱이 아니라 이 메타데이터를 검토하게 된다.
  # (taiken-trial 과 같은 이유다.)
  teaches: {{}}
  prerequisites: []
  source: beginner-curriculum korean/trial/lessons/{source}

# Generated by tools/import-trial-decks.py — edit the deck upstream and re-run.
"""

SRC_RE = re.compile(r'\bsrc="([^"]+)"')
LINKS_RE = re.compile(
    r'[ \t]*<link rel="stylesheet" href="(?:\.\./)*(?:runtime|shared)/css/([^"]+)">\n')
LEGACY_CONTROL_RE = re.compile(
    r'<span class="(?:slot|answer-space)"\s+data-sync-id="([^"]+)"')
STATIC_CONTROL_RES = {
    "slot": re.compile(r'<input class="slot-input"[^>]*\bdata-sync-id='),
    "input": re.compile(r'<input class="space-input"[^>]*\bdata-sync-id='),
    "free": re.compile(r'<textarea class="free-input"[^>]*\bdata-sync-id='),
    "build": re.compile(
        r'<span class="answer-space build-zone"[^>]*\bdata-sync-id='),
}


class ImportError_(Exception):
    pass


def audit_static_controls(raw: str, source: pathlib.Path | str) -> dict[str, int]:
    """Reject markup whose sync kind would exist only after JavaScript runs."""
    legacy = LEGACY_CONTROL_RE.findall(raw)
    if legacy:
        raise ImportError_(
            f"{source}: runtime-promoted control shell(s): {legacy[:3]}\n"
            "  fix the authoring HTML; import no longer rewrites controls")
    return {name: len(pattern.findall(raw))
            for name, pattern in STATIC_CONTROL_RES.items()}


# --------------------------------------------------------------------------- #
# 1. flatten refs
# --------------------------------------------------------------------------- #

def flatten(raw: str) -> tuple[str, list[str], list[str]]:
    scripts: list[str] = []
    assets: list[str] = []

    for url, name in AVATARS.items():
        if url in raw:
            raw = raw.replace(url, name)
            assets.append(name)

    def one_ref(match: re.Match) -> str:
        ref = match.group(1)
        if ref.startswith(("http://", "https://", "//", "data:", "#")):
            return match.group(0)
        name = pathlib.PurePosixPath(ref).name
        (scripts if ref.endswith(".js") else assets).append(name)
        return f'src="{name}"'

    raw = SRC_RE.sub(one_ref, raw)

    raw, n = LINKS_RE.subn(
        lambda m: f'  <link rel="stylesheet" href="{m.group(1)}">\n', raw)
    if not n:
        raise ImportError_("no runtime stylesheet <link> found to rewrite")

    return raw, sorted(set(scripts)), sorted(set(assets))


# --------------------------------------------------------------------------- #
# 2. bundle
# --------------------------------------------------------------------------- #

def find_asset(name: str, src: pathlib.Path) -> pathlib.Path:
    for root in (src / "trial" / "assets", REPO / "shared" / "assets"):
        hits = sorted(root.rglob(name)) if root.is_dir() else []
        if hits:
            return hits[0]
    raise ImportError_(
        f"asset not found: {name}\n"
        f"  looked in {src / 'trial' / 'assets'} and {REPO / 'shared' / 'assets'}")


def build_deck(target: pathlib.Path, page: str, scripts: list[str],
               assets: list[str], src: pathlib.Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    (target / "index.html").write_text(page, encoding="utf-8")

    for sheet in ("lesson-card.css", "trial.css"):
        shutil.copyfile(REPO / "shared" / "css" / sheet, target / sheet)

    for name in scripts:
        origin = REPO / "shared" / "js" / name
        if not origin.is_file():
            raise ImportError_(f"script not found: {origin}")
        shutil.copyfile(origin, target / name)

    for name in assets:
        shutil.copyfile(find_asset(name, src), target / name)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    upstream.add_argument(ap)
    args = ap.parse_args()

    try:
        src = upstream.resolve(args.upstream)
    except upstream.UpstreamMissing as exc:
        return _fail(str(exc))

    print(f"upstream: {src}\n")
    lessons = COURSE / "lessons"
    if lessons.exists():
        shutil.rmtree(lessons)

    try:
        for source, slug, week, title in DECKS:
            entry = src / "trial" / "lessons" / source
            if not entry.is_file():
                raise ImportError_(f"deck not found upstream: {entry}")

            page = entry.read_text(encoding="utf-8")
            tally = audit_static_controls(page, entry)
            page, scripts, assets = flatten(page)

            lesson = lessons / slug
            lesson.mkdir(parents=True, exist_ok=True)
            (lesson / "lesson.yaml").write_text(
                LESSON_YAML.format(slug=slug, week=week, source=source, **title),
                encoding="utf-8")

            # Both slots are mandatory — a lesson with only 수업용 leaves
            # PRESTUDY_LEMONBOARD_KEY empty and class creation fails at
            # /rooms/null/duplicate. The same deck fills both.
            for slot in ("lecture", "prestudy"):
                build_deck(lesson / slot, page, scripts, assets, src)

            counts = ", ".join(f"{k} {v}" for k, v in sorted(tally.items())) or "none"
            print(f"  {slug:<24} controls: {counts:<40} "
                  f"{len(scripts)} script(s), {len(assets)} asset(s)")
    except ImportError_ as exc:
        return _fail(str(exc))

    print("\nnow run:  python3 tools/validate.py --contract --env stage")
    return 0


def _fail(message: str) -> int:
    print(f"✗ {message}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
