#!/usr/bin/env python3
"""
Import the trial decks from the authoring tree into courses/kr/hangul-trial-test.

Upstream these four decks share one `runtime/` and build their input controls at
load. Neither survives deployment, so this does three transforms:

  1. static controls — every `.slot` / `.answer-space` shell that activities.js
     would promote at load is written into the file as the real
     `<input>` / `<textarea>` / build-zone.
  2. flatten refs   — `../../runtime/js/x.js` → `x.js`, `../assets/**/y` → `y`,
     and the two remote avatars become bundled local files.
  3. bundle         — `lesson-card.css`, `trial.css` and every referenced script
     and image are copied next to the deck. `build.py` merges the two sheets in
     link order into the single `lesson.css` grape renames per slot.

**(1) is the one that is not obvious.** lemonboard's validator parses the HTML
statically — `parseHTML(html)` via linkedom, no scripts run — while the binder
re-scans the live DOM on every publish. A `<span data-sync-id=…>` that only
becomes an `<input>` at load therefore resolves to no kind for the validator and
is dropped from the sync set, while working perfectly in class. That is a deck
which fails the merge gate and looks fine to whoever authored it, and you cannot
tell it apart from one that is genuinely broken. See CLAUDE.md.

The deck-local `activities.js` is this repo's own: it binds the controls above
rather than creating them. Everything else under `shared/js` is upstream's.

**This script owns `lessons/` completely** — it clears the directory each run so a
deck retired upstream disappears here, which means it writes `lesson.yaml` too.
Add a deck by adding a row to DECKS below.

Run `sync-from-authoring.py` first; this reads the runtime from upstream directly,
but the two should agree.

    python3 tools/import-trial-decks.py [--upstream PATH]
"""
from __future__ import annotations

import argparse
import html as html_mod
import pathlib
import re
import shutil
import sys

import upstream

REPO = upstream.REPO
COURSE = REPO / "courses" / "kr" / "hangul-trial-test"

# Bundled rather than fetched: a deck has to survive a locked-down classroom
# network, and these two are the only images the source leaves on a remote host.
AVATARS = {
    "https://respeak-lemonade.s3.ap-northeast-2.amazonaws.com/test/hana-avatar.jpg":
        "hana-avatar.jpg",
    "https://respeak-lemonade.s3.ap-northeast-2.amazonaws.com/test/haruka-avatar.jpg":
        "haruka-avatar.jpg",
}

MAX_TEXT = 2000

# source deck -> lesson directory, CLASS_WEEK, and the three-language title.
DECKS = [
    ("trial-1-hangul-short.html", "01-trial-hangul", 1,
     {"ko": "체험 · 초입문 한글",
      "en": "Trial · Hangul from zero",
      "ja": "体験レッスン 超入門"}),
    ("trial-2-patterns-short.html", "02-trial-self-intro", 2,
     {"ko": "체험 · 초급 자기소개",
      "en": "Trial · Introducing yourself",
      "ja": "体験レッスン 初級 · 自己紹介"}),
    ("trial-3-contextual-short.html", "03-trial-first-meeting", 3,
     {"ko": "체험 · 중급 우리, 어디서 본 적 있죠?",
      "en": "Trial · Haven't we met somewhere?",
      "ja": "体験レッスン 中級 · 第1話 どこかで会いましたよね？"}),
    ("trial-4-freetalking-short.html", "04-trial-free-talking", 4,
     {"ko": "체험 · 고급 프리토킹",
      "en": "Trial · Free talking",
      "ja": "体験レッスン 上級 · フリートーキング"}),
]

LESSON_YAML = """\
apiVersion: podo.curriculum/v1
kind: Lesson
metadata:
  slug: {slug}

spec:
  week: {week}

  title:
    ko: {ko}
    en: {en}
    ja: {ja}

  decks:
    lecture:  {{ entry: lecture/index.html }}
    prestudy: {{ entry: prestudy/index.html }}

  # 덱을 옮겨 온 것이라 teaches/outcome 은 비워 둔다 — 원본 기획 문서가 아니라
  # 덱에서 읽어낸 것을 적으면 리뷰가 실제 덱이 아니라 이 메타데이터를 검토하게 된다.
  # (taiken-trial 과 같은 이유다.)
  teaches: {{}}
  prerequisites: []
  source: beginner-curriculum korean/trial/lessons/{source}

# Generated by tools/import-trial-decks.py — edit the deck upstream and re-run.
"""

SHELL_RE = re.compile(
    r'<span class="(slot|answer-space)" data-sync-id="([^"]+)">([^<]*)</span>')
SRC_RE = re.compile(r'\bsrc="([^"]+)"')
LINKS_RE = re.compile(
    r'[ \t]*<link rel="stylesheet" href="(?:\.\./)*runtime/css/([^"]+)">\n')


class ImportError_(Exception):
    pass


def esc(value: str) -> str:
    return html_mod.escape(value, quote=True)


# --------------------------------------------------------------------------- #
# 1. static controls
# --------------------------------------------------------------------------- #

def classify(raw: str) -> dict[str, str]:
    """sync-id -> the control activities.js would build there.

    Ancestry decides it — an `.answer-space` inside a `.task-block` that carries
    chips is a build zone, not an input — so this reads a parsed tree. The
    rewrite below is text surgery, so the file keeps its own formatting and the
    diff against upstream stays readable.
    """
    try:
        from bs4 import BeautifulSoup
    except ImportError:                                        # pragma: no cover
        raise ImportError_(
            "beautifulsoup4 is required by this tool:  "
            "pip install -r tools/requirements.txt")

    soup = BeautifulSoup(raw, "html.parser")
    plan: dict[str, str] = {}
    for span in soup.select("span.answer-space[data-sync-id]"):
        block = span.find_parent(class_="task-block")
        chips = block.select(":scope > .choice") if block else []
        text = span.get_text().strip()
        plan[span["data-sync-id"]] = "build" if chips else ("input" if text else "free")
    for span in soup.select("span.slot[data-sync-id]"):
        plan[span["data-sync-id"]] = "slot"
    return plan


def render_control(kind: str, sync_id: str, answer: str) -> str:
    a, i = esc(answer), esc(sync_id)
    if kind == "slot":
        return (f'<input class="slot-input" type="text" data-sync-id="{i}" '
                f'data-answer="{a}" autocomplete="off" spellcheck="false">')
    if kind == "input":
        return ('<span class="answer-space as-input">'
                f'<input class="space-input" type="text" data-sync-id="{i}" '
                f'data-answer="{a}" autocomplete="off" spellcheck="false"></span>')
    if kind == "free":
        return ('<span class="answer-space as-input">'
                f'<textarea class="free-input" data-sync-id="{i}" rows="2" '
                f'spellcheck="false" maxlength="{MAX_TEXT}"></textarea></span>')
    if kind == "build":
        # The kind is named in the markup so the validator can resolve it; the
        # deck register()s "order" because chip order is not readable from the DOM.
        return (f'<span class="answer-space build-zone" data-sync-id="{i}" '
                f'data-sync-kind="order" data-a="{a}"></span>')
    raise ImportError_(f"unknown control kind: {kind}")


def statify(raw: str) -> tuple[str, dict[str, int]]:
    plan = classify(raw)
    tally: dict[str, int] = {}

    def sub(match: re.Match) -> str:
        css_class, sync_id, answer = match.group(1), match.group(2), match.group(3)
        kind = plan.get(sync_id)
        if not kind:
            raise ImportError_(f"shell {sync_id} was not classified")
        if (kind == "slot") != (css_class == "slot"):
            raise ImportError_(f"{sync_id}: class {css_class} but kind {kind}")
        tally[kind] = tally.get(kind, 0) + 1
        return render_control(kind, sync_id, answer.strip())

    out = SHELL_RE.sub(sub, raw)

    # A surviving shell is an element that carries data-sync-id and resolves to
    # nothing — silently private. Fail rather than ship it.
    left = re.findall(r'<span class="(?:slot|answer-space)"[^>]*>', out)
    if left:
        raise ImportError_(f"{len(left)} shell(s) not converted, e.g. {left[0]}")
    if len(plan) != sum(tally.values()):
        raise ImportError_(f"{len(plan)} shells planned, {sum(tally.values())} written")
    return out, tally


# --------------------------------------------------------------------------- #
# 2. flatten refs
# --------------------------------------------------------------------------- #

def flatten(raw: str) -> tuple[str, list[str], list[str]]:
    scripts: list[str] = []
    assets: list[str] = []

    for url, name in AVATARS.items():
        if url in raw:
            raw = raw.replace(url, name)
            assets.append(name)

    def one_ref(match: re.Match) -> str:
        ref = match.group(1)
        if ref.startswith(("http://", "https://", "//", "data:", "#")):
            return match.group(0)
        name = pathlib.PurePosixPath(ref).name
        (scripts if ref.endswith(".js") else assets).append(name)
        return f'src="{name}"'

    raw = SRC_RE.sub(one_ref, raw)

    raw, n = LINKS_RE.subn(
        lambda m: f'  <link rel="stylesheet" href="{m.group(1)}">\n', raw)
    if not n:
        raise ImportError_("no runtime stylesheet <link> found to rewrite")

    return raw, sorted(set(scripts)), sorted(set(assets))


# --------------------------------------------------------------------------- #
# 3. bundle
# --------------------------------------------------------------------------- #

def find_asset(name: str, src: pathlib.Path) -> pathlib.Path:
    for root in (src / "trial" / "assets", REPO / "shared" / "assets"):
        hits = sorted(root.rglob(name)) if root.is_dir() else []
        if hits:
            return hits[0]
    raise ImportError_(
        f"asset not found: {name}\n"
        f"  looked in {src / 'trial' / 'assets'} and {REPO / 'shared' / 'assets'}")


def build_deck(target: pathlib.Path, page: str, scripts: list[str],
               assets: list[str], src: pathlib.Path) -> None:
    target.mkdir(parents=True, exist_ok=True)
    (target / "index.html").write_text(page, encoding="utf-8")

    for sheet in ("lesson-card.css", "trial.css"):
        shutil.copyfile(src / "runtime" / "css" / sheet, target / sheet)

    for name in scripts:
        origin = ((REPO / "tools" / "deck-runtime" / "activities.js")
                  if name == "activities.js" else (src / "runtime" / "js" / name))
        if not origin.is_file():
            raise ImportError_(f"script not found: {origin}")
        shutil.copyfile(origin, target / name)

    for name in assets:
        shutil.copyfile(find_asset(name, src), target / name)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    upstream.add_argument(ap)
    args = ap.parse_args()

    try:
        src = upstream.resolve(args.upstream)
    except upstream.UpstreamMissing as exc:
        return _fail(str(exc))

    print(f"upstream: {src}\n")
    lessons = COURSE / "lessons"
    if lessons.exists():
        shutil.rmtree(lessons)

    try:
        for source, slug, week, title in DECKS:
            entry = src / "trial" / "lessons" / source
            if not entry.is_file():
                raise ImportError_(f"deck not found upstream: {entry}")

            page, tally = statify(entry.read_text(encoding="utf-8"))
            page, scripts, assets = flatten(page)

            lesson = lessons / slug
            lesson.mkdir(parents=True, exist_ok=True)
            (lesson / "lesson.yaml").write_text(
                LESSON_YAML.format(slug=slug, week=week, source=source, **title),
                encoding="utf-8")

            # Both slots are mandatory — a lesson with only 수업용 leaves
            # PRESTUDY_LEMONBOARD_KEY empty and class creation fails at
            # /rooms/null/duplicate. The same deck fills both.
            for slot in ("lecture", "prestudy"):
                build_deck(lesson / slot, page, scripts, assets, src)

            counts = ", ".join(f"{k} {v}" for k, v in sorted(tally.items())) or "none"
            print(f"  {slug:<24} controls: {counts:<40} "
                  f"{len(scripts)} script(s), {len(assets)} asset(s)")
    except ImportError_ as exc:
        return _fail(str(exc))

    print("\nnow run:  python3 tools/validate.py --contract --env stage")
    return 0


def _fail(message: str) -> int:
    print(f"✗ {message}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
