#!/usr/bin/env python3
"""
Promote the sandbox report deck into courses/kr/report-test.

`sandbox/trial/reports/trial-1-report.html` is the 니즈 파악 → 리포트 & 플랜 deck.
It reaches sideways for everything — `../../../shared/css`, `../../../shared/js`,
`../assets/**` — and two of its faces live on S3. None of that survives the upload
slot, which flattens every zip entry into one GCS prefix, so this does three things:

  1. flatten refs  — `../../../shared/js/x.js` → `x.js`, `../assets/**/y.png` → `y.png`,
     and the two remote avatars become bundled local files.
  2. bundle        — every referenced sheet, script and image is copied next to the
     deck in both slots. `build.py` merges the two sheets in link order into the
     single `lesson.css` grape renames per slot.
  3. audit         — every `data-sync-id` is resolved against lemonboard's own rules
     before anything is written.

**(3) is the one that is not obvious.** An element carrying `data-sync-id` and
nothing else resolves to no kind, is dropped from the sync set, and fails silently —
the activity works on one screen and the other person never sees it. The deck as
authored is clean, and this check is here so it stays that way: promoting it again
after an edit upstream re-runs the audit rather than trusting it. See CLAUDE.md.

Unlike `import-trial-decks.py` this reads no external authoring tree — the source is
this repo's own `sandbox/`, which `tools/model.py` refuses to walk. Moving a deck out
of there and into `courses/` is exactly what promoting means.

**This script owns the course's `lessons/` completely** — it clears the directory each
run, which means it writes `lesson.yaml` too. `course.yaml` is hand-held: identity
(`classLevel` / `lessonTime`) is not something a re-import should be able to move.

    python3 tools/import-report-deck.py
"""
from __future__ import annotations

import pathlib
import re
import shutil
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
COURSE = REPO / "courses" / "kr" / "report-test"
SOURCE = REPO / "sandbox" / "trial" / "reports" / "trial-1-report.html"

# Where a flattened basename is looked up, in order.
ASSET_ROOTS = (REPO / "sandbox" / "trial" / "assets", REPO / "shared" / "assets")
SCRIPT_ROOT = REPO / "shared" / "js"
CSS_ROOT = REPO / "shared" / "css"

# Bundled rather than fetched: a deck has to survive a locked-down classroom
# network, and these two are the only images the source leaves on a remote host.
# Both already sit in shared/assets, so this needs no network either.
AVATARS = {
    "https://respeak-lemonade.s3.ap-northeast-2.amazonaws.com/test/hana-avatar.jpg":
        "hana-avatar.jpg",
    "https://respeak-lemonade.s3.ap-northeast-2.amazonaws.com/test/haruka-avatar.jpg":
        "haruka-avatar.jpg",
}

# source deck -> lesson directory, CLASS_WEEK, and the three-language title.
DECKS = [
    ("trial-1-report.html", "01-trial-report", 1,
     {"ko": "체험 · 니즈 파악과 리포트",
      "en": "Trial · Needs and report",
      "ja": "体験 · ニーズ把握＆レポート"}),
]

LESSON_YAML = """\
apiVersion: podo.curriculum/v1
kind: Lesson
metadata:
  slug: {slug}

spec:
  week: {week}

  title:
    ko: {ko}
    en: {en}
    ja: {ja}

  decks:
    lecture:  {{ entry: lecture/index.html }}
    prestudy: {{ entry: prestudy/index.html }}

  # 덱을 옮겨 온 것이라 teaches/outcome 은 비워 둔다 — 원본 기획 문서가 아니라
  # 덱에서 읽어낸 것을 적으면 리뷰가 실제 덱이 아니라 이 메타데이터를 검토하게 된다.
  # (taiken-trial · hangul-trial-test 와 같은 이유다.)
  teaches: {{}}
  prerequisites: []
  source: sandbox/trial/reports/{source}

# Generated by tools/import-report-deck.py — edit the deck in sandbox/ and re-run.
"""

SRC_RE = re.compile(r'\bsrc="([^"]+)"')
LINK_RE = re.compile(r'[ \t]*<link rel="stylesheet" href="([^"]+)">\n')
REMOTE = ("http://", "https://", "//", "data:", "#")

# The report deck writes its controls straight into the HTML, so nothing should be
# promoted at load. A surviving shell would resolve to no kind for the validator
# while working fine in class — the exact failure that is invisible to whoever
# authored it.
SHELL_RE = re.compile(r'<span class="(?:slot|answer-space)"[^>]*\bdata-sync-id=')


class ImportFailed(Exception):
    pass


def _fail(message: str) -> int:
    print(f"✗ {message}")
    return 1


# --------------------------------------------------------------------------- #
# audit — lemonboard's kind resolution, run statically
# --------------------------------------------------------------------------- #

def resolve_kinds(raw: str) -> dict[str, str]:
    """sync-id -> the kind lemonboard's binder will infer, or raise.

    Mirrors html-sync/kinds.ts in order: an explicit data-sync-kind wins, then a
    form control is `value`, then a [data-sync-option] descendant is `selection`,
    then a data-sync-state attribute is `toggle`. Anything left resolves to
    nothing and is silently private, so it is an error here instead.
    """
    try:
        from bs4 import BeautifulSoup
    except ImportError:                                        # pragma: no cover
        raise ImportFailed(
            "beautifulsoup4 is required by this tool:  "
            "pip install -r tools/requirements.txt")

    soup = BeautifulSoup(raw, "html.parser")
    kinds: dict[str, str] = {}
    unresolved: list[str] = []

    for el in soup.select("[data-sync-id]"):
        sync_id = el["data-sync-id"]
        if sync_id in kinds:
            raise ImportFailed(f"duplicate data-sync-id: {sync_id}")
        if el.has_attr("data-sync-kind"):
            kinds[sync_id] = el["data-sync-kind"]
        elif el.name in ("input", "textarea", "select"):
            kinds[sync_id] = "value"
        elif el.select_one("[data-sync-option]"):
            kinds[sync_id] = "selection"
        elif el.has_attr("data-sync-state"):
            kinds[sync_id] = "toggle"
        else:
            unresolved.append(f"<{el.name} data-sync-id=\"{sync_id}\">")

    if unresolved:
        raise ImportFailed(
            "these carry data-sync-id but resolve to no kind — they would be "
            "dropped from the sync set with no error:\n    "
            + "\n    ".join(unresolved))
    if not kinds:
        raise ImportFailed("no data-sync-id found at all; is this the right deck?")
    return kinds


# --------------------------------------------------------------------------- #
# flatten refs
# --------------------------------------------------------------------------- #

def flatten(raw: str) -> tuple[str, list[str], list[str], list[str]]:
    scripts: list[str] = []
    assets: list[str] = []
    sheets: list[str] = []
    origins: dict[str, str] = {}

    def claim(name: str, ref: str) -> None:
        """Flattening means one GCS prefix, so two folders cannot share a basename."""
        previous = origins.setdefault(name, ref)
        if previous != ref:
            raise ImportFailed(
                f"basename collision on {name}: {previous} and {ref} would "
                f"flatten onto each other")

    # Rewrite first, then let one_src below pick the results up as ordinary local
    # refs — that way the bundling and the collision check have a single path.
    for url, name in AVATARS.items():
        raw = raw.replace(url, name)

    def one_src(match: re.Match) -> str:
        ref = match.group(1)
        if ref.startswith(REMOTE):
            return match.group(0)
        name = pathlib.PurePosixPath(ref).name
        claim(name, ref)
        (scripts if ref.endswith(".js") else assets).append(name)
        return f'src="{name}"'

    raw = SRC_RE.sub(one_src, raw)

    def one_link(match: re.Match) -> str:
        ref = match.group(1)
        if ref.startswith(REMOTE):
            return match.group(0)
        name = pathlib.PurePosixPath(ref).name
        claim(name, ref)
        sheets.append(name)
        return f'  <link rel="stylesheet" href="{name}">\n'

    raw, n = LINK_RE.subn(one_link, raw)
    if not sheets:
        raise ImportFailed(f"no local stylesheet <link> found to rewrite ({n} seen)")

    left = SHELL_RE.findall(raw)
    if left:
        raise ImportFailed(f"{len(left)} runtime-promoted shell(s) found; "
                           "write the real control into the HTML instead")

    return raw, sorted(set(sheets)), sorted(set(scripts)), sorted(set(assets))


# --------------------------------------------------------------------------- #
# bundle
# --------------------------------------------------------------------------- #

def find_asset(name: str) -> pathlib.Path:
    for root in ASSET_ROOTS:
        hits = sorted(root.rglob(name)) if root.is_dir() else []
        if hits:
            return hits[0]
    roots = " and ".join(str(r.relative_to(REPO)) for r in ASSET_ROOTS)
    raise ImportFailed(f"asset not found: {name}\n  looked in {roots}")


def build_deck(target: pathlib.Path, page: str, sheets: list[str],
               scripts: list[str], assets: list[str]) -> None:
    target.mkdir(parents=True, exist_ok=True)
    (target / "index.html").write_text(page, encoding="utf-8")

    for name in sheets:
        origin = CSS_ROOT / name
        if not origin.is_file():
            raise ImportFailed(f"stylesheet not found: {origin}")
        shutil.copyfile(origin, target / name)

    for name in scripts:
        origin = SCRIPT_ROOT / name
        if not origin.is_file():
            raise ImportFailed(f"script not found: {origin}")
        shutil.copyfile(origin, target / name)

    for name in assets:
        shutil.copyfile(find_asset(name), target / name)


def main() -> int:
    lessons = COURSE / "lessons"
    if lessons.exists():
        shutil.rmtree(lessons)

    try:
        for source, slug, week, title in DECKS:
            entry = SOURCE.parent / source
            if not entry.is_file():
                raise ImportFailed(f"deck not found: {entry}")

            raw = entry.read_text(encoding="utf-8")
            kinds = resolve_kinds(raw)
            page, sheets, scripts, assets = flatten(raw)

            lesson = lessons / slug
            lesson.mkdir(parents=True, exist_ok=True)
            (lesson / "lesson.yaml").write_text(
                LESSON_YAML.format(slug=slug, week=week, source=source, **title),
                encoding="utf-8")

            # Both slots are mandatory — a lesson with only 수업용 leaves
            # PRESTUDY_LEMONBOARD_KEY empty and class creation fails at
            # /rooms/null/duplicate. The same deck fills both.
            for slot in ("lecture", "prestudy"):
                build_deck(lesson / slot, page, sheets, scripts, assets)

            tally: dict[str, int] = {}
            for kind in kinds.values():
                tally[kind] = tally.get(kind, 0) + 1
            counts = ", ".join(f"{k} {v}" for k, v in sorted(tally.items()))
            print(f"  {slug:<20} sync: {counts:<34} "
                  f"{len(sheets)} sheet(s), {len(scripts)} script(s), "
                  f"{len(assets)} asset(s)")
    except ImportFailed as exc:
        return _fail(str(exc))

    print("\nnow run:  python3 tools/validate.py --contract --env stage")
    return 0


if __name__ == "__main__":
    sys.exit(main())
