#!/usr/bin/env python3
"""
Keep `shared/view/report.html` carrying the same report markup the decks ship.

The trial decks draw the report during the lesson; the app reopens the same
report afterwards. Both have to be the same document, so there is exactly one
copy of the markup that matters — the one in the deck — and this tool lifts it
into the viewer rather than letting anyone maintain a second copy by hand.

    python3 tools/report-viewer.py            # write the viewer from the decks
    python3 tools/report-viewer.py --check    # fail if it is out of date (CI)

Why the built deck and not the draft: `courses/` is what actually ships, and its
asset URLs are already resolved against the shared runtime. The viewer lives
*inside* that runtime, so those absolute URLs become plain relative ones and the
viewer is correct for whatever tag it is published under — no second place
pinning a version.

Every trial deck that has a report must carry the identical block; a report that
drifted per level would be four documents wearing one name. That is checked here
rather than assumed.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import model

BEGIN = "<!-- BEGIN report block · generated by tools/report-viewer.py — do not edit -->"
END = "<!-- END report block -->"

VIEWER = model.REPO / "shared" / "view" / "report.html"

# 리포트를 싣고 있는 덱. 없는 덱(영어 체험)은 튜터 채점만 하고 리포트 면이 없다 —
# 그쪽 리포트는 수업이 끝난 뒤 챗으로 간다는 것이 그 덱의 설계다.
# 예습 덱도 같은 리포트 면을 싣는다(현재 8벌: 레슨 4 × lecture·prestudy). 여덟이
# 모두 같아야 하고, 하나만 검사하면 나머지가 조용히 갈라진다.
DECK_GLOB = "courses/kr/trial-lv*/lessons/*/*/index.html"


class ViewerError(Exception):
    pass


def report_block(html: str, where: str) -> str:
    """The `.rep-page` element, whole, by matching <div> nesting."""
    start = html.find('<div class="section rep-page')
    if start < 0:
        raise ViewerError(f"{where}: no .rep-page block")
    depth = 0
    for m in re.finditer(r"<(/?)div\b", html[start:]):
        depth += 1 if m.group(1) == "" else -1
        if depth == 0:
            close = html.find(">", start + m.end() - 1) + 1
            return html[start:close]
    raise ViewerError(f"{where}: .rep-page is never closed")


# 튜터가 조작하는 자리. body.teaching 에서만 보이므로 뷰어에서도 어차피 감춰지지만,
# 학생이 여는 문서에 튜터의 조작면을 실어 보낼 이유가 없다. .axsteps 를 빼는 데는
# 이유가 하나 더 있다 — report.js 가 거기 적힌 data-say 로 레벨 카드의 ✓ 줄을 짓는데,
# 그 문장은 제품마다 다르다(한국어는 「助詞と語尾」, 영어는 「時制や冠詞」). 한국어 덱에서
# 잘라 온 마크업을 그대로 두면 영어 리포트가 한국어 문법 이야기를 하게 된다.
# 뷰어에서는 그 표를 로케일 파일(report-{ja,en}.js 의 BAND)에서 받는다.
TUTOR_ONLY = ("lvcheck", "axsteps", "rep-send")


def strip_tutor_blocks(block: str) -> str:
    for cls in TUTOR_ONLY:
        while True:
            m = re.search(r'\n\s*<div class="' + re.escape(cls) + r'"', block)
            if not m:
                break
            start = m.start()
            depth = 0
            for d in re.finditer(r"<(/?)div\b", block[m.start():]):
                depth += 1 if d.group(1) == "" else -1
                if depth == 0:
                    close = block.find(">", m.start() + d.end() - 1) + 1
                    block = block[:start] + block[close:]
                    break
            else:
                raise ViewerError(f".{cls} is never closed")

    # 못 걷어낸 것이 하나라도 남으면 조용히 넘어가지 않는다. 남는 순간 두 가지가
    # 한꺼번에 깨진다 — 학생이 볼 문서에 튜터 조작면이 실리고, report.js 가 레벨
    # 카드의 ✓ 줄을 로케일 표가 아니라 그 마크업(.axq)에서 읽어 버려서 영어 리포트가
    # 한국어 문법 이야기를 하게 된다. 마크업의 class 가 바뀌면 여기서 멈춘다.
    left = [cls for cls in TUTOR_ONLY if re.search(r'class="[^"]*\b' + re.escape(cls) + r'\b', block)]
    if left:
        raise ViewerError(
            f"tutor-only block(s) survived stripping: {', '.join(left)}\n"
            f"    덱의 class 이름이 바뀌었을 수 있다 — TUTOR_ONLY 와 맞춰라")
    return block


def to_runtime_relative(block: str, prefix: str, where: str) -> str:
    """Absolute shared-runtime URLs -> paths relative to the viewer inside the tag.

    Anything else that loads is a defect for this artifact, not a detail to paper
    over: the viewer is served from the runtime tag alone, so a deck-local image
    would 404 there. Surfacing it here is the whole point — the fix is to move the
    asset into `shared/assets/` (repoint-shared.py), not to special-case it.
    """
    out = block.replace(prefix, "../")
    stray = [u for u in re.findall(r'\b(?:src|href)="([^"]+)"', out)
             if not u.startswith(("../", "#", "data:"))]
    if stray:
        raise ViewerError(
            f"{where}: report asset is not on the shared runtime: {', '.join(sorted(set(stray))[:5])}\n"
            f"    move it into shared/assets/ so the viewer can serve it too")
    return out


def canonical_block() -> str:
    curriculum = model.load_curriculum()
    rt = curriculum["spec"]["sharedRuntime"]
    prefix = f"{rt['baseUrl'].rstrip('/')}{rt.get('join', '@')}{rt['version']}/"

    decks = sorted(model.REPO.glob(DECK_GLOB))
    if not decks:
        raise ViewerError(f"no decks matched {DECK_GLOB}")

    blocks: dict[str, str] = {}
    for deck in decks:
        html = deck.read_text(encoding="utf-8")
        if '<div class="section rep-page' not in html:
            continue
        rel = deck.relative_to(model.REPO).as_posix()
        blocks[rel] = to_runtime_relative(
            strip_tutor_blocks(report_block(html, rel)), prefix, rel)

    if not blocks:
        raise ViewerError("no trial deck carries a report block")

    first = next(iter(blocks))
    for rel, block in blocks.items():
        if block != blocks[first]:
            raise ViewerError(
                f"trial decks carry different report markup:\n"
                f"    {first}\n    {rel}\n"
                f"    the report is one document — fix the drafts so they match, then re-promote")
    return blocks[first]


# 제품 하나 = 로케일 표 하나 + 그 표를 쓰는 덱들.
LOCALES = {
    "shared/js/report-ja.js": "courses/kr/trial-lv*/lessons/*/lecture/index.html",
    "shared/js/report-en.js": "courses/en/trial-lv*/lessons/*/lecture/index.html",
}
AXES = ("acc", "voc", "flu", "pron", "lis")


def deck_bands(pattern: str) -> dict[str, list[str]]:
    """The five `.axq` option sets a deck offers the tutor, by axis."""
    for deck in sorted(model.REPO.glob(pattern)):
        html = deck.read_text(encoding="utf-8")
        found = {}
        for m in re.finditer(r'<div class="axq"[^>]*data-ax="(\w+)"(.*?)</div>\s*</div>',
                             html, re.S):
            says = re.findall(r'data-say="([^"]*)"', m.group(2))
            if says:
                found[m.group(1)] = says
        if found:
            return found
    return {}


def locale_bands(path: pathlib.Path) -> dict[str, list[str]]:
    """The BAND table a locale file declares. Tolerant of formatting, not of JS."""
    src = path.read_text(encoding="utf-8")
    m = re.search(r"\bBAND:\s*\{", src)
    if not m:
        return {}
    depth, i = 0, m.end() - 1
    for j in range(i, len(src)):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                body = src[i:j + 1]
                break
    else:
        raise ViewerError(f"{path.name}: BAND is never closed")
    out = {}
    for ax in AXES:
        a = re.search(r"\b" + ax + r"\s*:\s*\[(.*?)\]", body, re.S)
        if a:
            out[ax] = re.findall(r'"((?:[^"\\]|\\.)*)"', a.group(1))
    return out


def deck_headline(pattern: str) -> str | None:
    for deck in sorted(model.REPO.glob(pattern)):
        m = re.search(r'<h2 class="rhead-t">(.*?)</h2>',
                      deck.read_text(encoding="utf-8"), re.S)
        if m:
            return m.group(1)
    return None


def locale_headline(path: pathlib.Path) -> str | None:
    m = re.search(r'headline:\s*"((?:[^"\\]|\\.)*)"', path.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def check_band_tables() -> list[str]:
    """The level card's ✓ lines are written once, in the deck, and mirrored in the
    locale table so the viewer can draw them without carrying the tutor's picker.
    Two copies only stay one document if something compares them."""
    problems = []
    for rel, pattern in LOCALES.items():
        path = model.REPO / rel
        if not path.is_file():
            continue
        want, have = deck_bands(pattern), locale_bands(path)
        if not want:
            continue
        if not have:
            problems.append(f"{rel}: no BAND table — the viewer cannot draw the ✓ lines "
                            f"for this product (copy them from {pattern})")
            continue
        # 머리글도 같은 부류다 — 덱 마크업이 정본이고 표는 그 사본이다.
        deck_head = deck_headline(pattern)
        loc_head = locale_headline(path)
        if deck_head and loc_head and deck_head != loc_head:
            problems.append(f"{rel}: text.headline does not match the deck's .rhead-t\n"
                            f"    deck   {deck_head}\n    locale {loc_head}")
        for ax in AXES:
            if want.get(ax) != have.get(ax):
                problems.append(
                    f"{rel}: BAND.{ax} does not match the deck's .axq data-say\n"
                    f"    deck   {want.get(ax)}\n    locale {have.get(ax)}")
    return problems


def render(block: str) -> str:
    shell = VIEWER.read_text(encoding="utf-8")
    i, j = shell.find(BEGIN), shell.find(END)
    if i < 0 or j < 0:
        raise ViewerError(f"{VIEWER}: markers are gone — restore {BEGIN} / {END}")
    return shell[:i + len(BEGIN)] + "\n" + block + "\n" + shell[j:]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit non-zero if the viewer is stale")
    args = ap.parse_args()

    try:
        want = render(canonical_block())
        band_problems = check_band_tables()
    except ViewerError as exc:
        print(f"✗ report viewer: {exc}")
        return 1

    if band_problems:
        for p in band_problems:
            print(f"✗ report viewer: {p}")
        return 1
    print("✓ report viewer — BAND tables match their decks")

    have = VIEWER.read_text(encoding="utf-8")
    if have == want:
        print(f"✓ report viewer — shared/view/report.html matches the decks")
        return 0
    if args.check:
        print("✗ report viewer: shared/view/report.html is out of date with the trial decks\n"
              "    python3 tools/report-viewer.py")
        return 1
    VIEWER.write_text(want, encoding="utf-8")
    print(f"✓ report viewer — rewrote shared/view/report.html ({len(want)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
