#!/usr/bin/env python3
"""Build the lean Core evidence ledger from the authoritative TOC.

The ledger is intentionally a triage instrument. It connects every lesson to
the nearest source category without turning a broad source match into a claim
that the lesson, model lines, or exact CEFR band have been validated.
"""

from __future__ import annotations

from collections import Counter
import pathlib

import track_parsers


ROOT = pathlib.Path(__file__).resolve().parents[3] / "sandbox/drafts/en"
OUT = ROOT / "reference" / "core-evidence-ledger.md"
GENERATED = "Generated by `tools/authoring/en/build_core_evidence_ledger.py` — do not edit this file."


# One deliberately broad source assignment per unit keeps the ledger readable.
# Row-level exceptions below capture the cases where that would conceal a
# consequential mismatch.
UNIT_EVIDENCE = {
    1: ("A1 · Giving personal information; Greetings; `be`; personal pronouns", "Information exchange · pp. 78–79", "local-stage"),
    2: ("A1 · Directions; numbers; `there is/are`; place prepositions", "Information exchange · pp. 78–79", "local-stage"),
    3: ("A1 · Describing habits and routines; present simple; questions", "Conversation · pp. 73–74", "supported"),
    4: ("A1 grammar (`can/could`, `I'd like`); A2 function (Requests)", "Obtaining goods and services · pp. 77–78", "mixed"),
    5: ("A1 present continuous; A2 present continuous for future", "Conversation · pp. 73–74", "mixed"),
    6: ("A2 · Describing past experiences; past simple/continuous; sequential linkers", "Sustained monologue: describing experience · pp. 62–63", "supported"),
    7: ("A2 · Future time; obligation; requests; suggestions; modals", "Goal-oriented co-operation · pp. 76–77", "supported"),
    8: ("A2 · Describing things; comparison; `too/enough`", "Information exchange · pp. 78–79", "supported"),
    9: ("A2 present perfect; B1 present perfect continuous and past contrast", "Conversation · pp. 73–74", "mixed"),
    10: ("B1 · Opinions; cause/effect and contrast; relative clauses; conditionals", "Informal discussion · pp. 74–75", "supported"),
    11: ("A2 Requests; B1 managing interaction, passives and extended questions", "Obtaining goods and services / Information exchange · pp. 77–79", "mixed"),
    12: ("B1 · Speculating; conditionals; wish; deduction; reported speech", "Informal discussion · pp. 74–75", "supported"),
    13: ("B1 · past modals; past perfect; past habits", "Sustained monologue: describing experience · pp. 62–63", "supported"),
    14: ("B2 future continuous/perfect; no direct Core Inventory causative item", "Information exchange · pp. 78–79", "mixed"),
    15: ("B2 · opinions, disagreement, interaction management and workplace discourse", "Formal discussion (meetings) · pp. 75–76", "function-supported"),
    16: ("B2 · adjectives/adverbs and differentiated vocabulary; quantity functions are indirect", "Information exchange · pp. 78–79", "partial"),
    17: ("B2 · expressing and qualifying disagreement; C1 hedging overlap", "Formal discussion (meetings) · pp. 75–76", "function-supported"),
    18: ("B2/C1 · cause/effect, evidence, consequences and conditional framing", "Sustained monologue: putting a case · pp. 64–65", "function-supported"),
    19: ("B2 emphasis functions; C1 negative-adverbial inversion", "Thematic development / propositional precision · pp. 139–142", "mixed"),
    20: ("C1 · formal/informal register and differentiated vocabulary", "Sociolinguistic appropriateness · pp. 136–137", "function-supported"),
    21: ("C1 · abstract ideas, argument, concession, evaluation and counterargument", "Sustained monologue: putting a case · pp. 64–65", "function-supported"),
    22: ("C1 · hedging, vague language, reaction and implied stance", "Sociolinguistic appropriateness / flexibility · pp. 136–139", "function-supported"),
}


ROW_OVERRIDES = {
    18: ("A1 · `Can/can't` (ability)", "Information exchange / Conversation · pp. 73–74, 78–79", "supported", "The primary function and modal form now match the beginner inventory; exact model-line naturalness remains a separate check."),
    20: ("A1 `can/could`; Requests appears at A2", "Obtaining goods and services · pp. 77–78", "bounded-early", "Approved pilot: retain as a bounded request chunk; do not generalise this to A2 request mastery."),
    24: ("A2 · Requests; B1 · Checking understanding / managing interaction", "Asking for clarification · pp. 70–71", "bounded-early", "The repair chunks are intentionally taught before broader B1 interaction management."),
    27: ("A1/A2 · `like/love/hate` + `-ing` for preferences", "Conversation · pp. 73–74", "supported", "The rewritten lesson now owns activity preferences and the verb-plus-`-ing` complement."),
    28: ("A2 · Invitations; `would like` + infinitive", "Conversation · pp. 73–74", "supported", "The lesson preserves availability language and now adds the missing invitation function."),
    52: ("B1 · Present perfect continuous", "Conversation · pp. 73–74", "supported", "The working A2→B1 label should be read conservatively as B1 for productive control of this form."),
    62: ("B1 · questions and interaction management", "Information exchange · pp. 78–79", "supported", "Public Cambridge EGP guidance explicitly identifies indirect questions at B1."),
    76: ("No direct Core Inventory item for the service causative", "Obtaining goods and services · pp. 77–78", "form-supported-band-open", "Cambridge Grammar Today attests both have/get + object + participle and identifies the construction as common in speech. No exact EGP productive-band result was located, so B1+ remains a working placement."),
    77: ("B1/B2 · service problems, expectations and follow-up", "Obtaining goods and services · pp. 77–78", "supported", "The EGP places past arrangements that may not have happened at B1 and expectation/obligation at B2. B1+ is a defensible bridge placement; the follow-up question reuses already-owned present-perfect and indirect-question language."),
    79: ("B1/B2 · workplace estimates and qualified prediction", "Goal-oriented co-operation / Information exchange · pp. 76–79", "supported", "Cambridge labels probability/expectation should as B1 and gives a service-ready-by-deadline example. The replacement is no longer a future-perfect level mismatch."),
    84: ("B1/B2 · formal discussion and hedged requests", "Formal discussion (meetings) · pp. 75–76", "supported", "Cambridge labels wonder used to begin a polite request as B1 and Grammar Today attests the exact past-continuous polite-distance frame. B1+ is conservative."),
    105: ("B2 · comparison with adjectives/adverbs", "Propositional precision / thematic development · pp. 139–142", "form-supported-band-open", "Cambridge Grammar Today directly attests repeated the + comparative clauses for linked change. No exact EGP productive-band result was located, so B2 remains a working placement rather than a certification claim."),
    112: ("C1 · register, impact and repair", "Sociolinguistic appropriateness · pp. 136–137", "function-supported", "The risky disagreement formula has been replaced by a productive impact-and-intent repair sequence; exact exponent evidence remains open."),
}


GRANULAR_RESULTS = {
    62: "public EGP match · indirect questions at B1",
    76: "Cambridge usage match · no exact EGP band result",
    77: "EGP match · past expectation B1; expectation/obligation B2",
    79: "Cambridge Dictionary match · probability/expectation `should` B1",
    84: "Cambridge Dictionary/Grammar Today match · polite `wonder` request B1",
    105: "Cambridge usage match · no exact EGP band result",
}


def _granular_result(number: int) -> str:
    return GRANULAR_RESULTS.get(number, "not selected · broad-source alignment only")


def _cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def evidence_for(lesson: dict) -> tuple[str, str, str, str]:
    inventory, cefr, status = UNIT_EVIDENCE[lesson["unitNo"]]
    note = "Broad source match only; exact pattern level and spoken naturalness remain unproven."
    return ROW_OVERRIDES.get(lesson["no"], (inventory, cefr, status, note))


def render(lessons: list[dict]) -> str:
    statuses = Counter(evidence_for(lesson)[2] for lesson in lessons)
    lines = [
        "# Core Evidence Ledger",
        "",
        f"> **{GENERATED}**",
        ">",
        "> This is a compact **triage ledger**, not a CEFR certification or naturalness audit. The Core TOC",
        "> remains authoritative for curriculum content; this file makes source support and uncertainty visible.",
        "",
        "## What this ledger proves",
        "",
        "- Every one of the 122 stable Core IDs is connected to a Core Inventory category or an explicit gap.",
        "- Every can-do is connected to the nearest CEFR Companion Volume scale, or a broad scale when no",
        "  one-to-one descriptor exists.",
        "- Consequential mismatches are called out rather than averaged away at unit level.",
        "- The restored English Grammar Profile app and other first-party Cambridge grammar sources resolve",
        "  the previously named high-risk rows. A granular result is not invented for the remaining broad-source",
        "  rows; those receive exact follow-up only when native review or a band decision makes it consequential.",
        "",
        "It does **not** prove that a model line is natural, frequent, teachable, or retrievable. Those claims",
        "belong to the corpus/naturalness audit and learner pilots.",
        "",
        "## Source and decision rules",
        "",
        "- **Core Inventory locator:** *A Core Inventory for General English*, essential guide, printed pp. 12–13.",
        "  The inventory is selective guidance for teaching, not a mastery test or prescribed sequence. A later",
        "  British Council validation study found many level assignments inconclusive, so a match is supporting",
        "  evidence rather than a verdict.",
        "- **CEFR locator:** *CEFR Companion Volume* (2020), named scale and printed page shown below.",
        "- **Current band:** copied from the live TOC at generation time.",
        "- **Status:** `supported` is a broad source alignment, not proof of the exact two patterns. `mixed`,",
        "  `partial`, `bounded-early`, and `form-supported-band-open` require human disposition before a CEFR",
        "  claim is frozen. `function-supported` means the communicative move is sourced but its exponent is not.",
        "- When sources disagree, use the more conservative productive band unless the earlier item is explicitly",
        "  approved as a bounded lexical chunk.",
        "",
        "Primary sources: [Core Inventory](https://www.eaquals.org/wp-content/uploads/EAQUALS_British_Council_Core_Curriculum_April2011.pdf) · "
        "[CEFR Companion Volume](https://rm.coe.int/common-european-framework-of-reference-for-languages-learning-teaching/16809ea0d4) · "
        "[Core Inventory validation study](https://www.britishcouncil.org/research-insight/validating-core-inventory-general-english) · "
        "[English Grammar Profile Online](https://englishprofile.org/?menu=egp-online) · "
        "[Cambridge EGP methodology](https://www.cambridge.org/elt/blog/2015/11/11/introducing-english-grammar-profile-1-building-profile/) · "
        "[public indirect-question example](https://www.cambridge.org/elt/blog/2021/06/23/using-cefr-criterial-features-for-grammar-instruction/) · "
        "[Cambridge Grammar Today](https://dictionary.cambridge.org/grammar/british-grammar/)",
        "",
        "Priority-row locators: [service causative](https://dictionary.cambridge.org/grammar/british-grammar/passive-other-forms) · "
        "[`should` for probability](https://dictionary.cambridge.org/grammar/british-grammar/should) · "
        "[polite past-form distancing](https://dictionary.cambridge.org/grammar/british-grammar/politeness_2) · "
        "[linked comparatives](https://dictionary.cambridge.org/grammar/british-grammar/comparison-adjectives-)",
        "",
        "## Health",
        "",
        f"- Rows: **{len(lessons)} / 122**",
        "- Statuses: " + " · ".join(f"**{name}: {count}**" for name, count in sorted(statuses.items())),
        f"- Granular first-party results: **{len(GRANULAR_RESULTS)} / {len(lessons)}**",
        "- Named priority rows resolved: **Core 76, 77, 79, 84 and 105**",
        "- Productive-band evidence still open: **Core 76 and Core 105**; their forms are attested, but the",
        "  present B1+/B2 placements remain working curriculum bands pending learner performance.",
        "",
        "## Rows",
        "",
        "| ID | Current band | Can-do | Core Inventory evidence | CEFR evidence | Granular first-party result | Status | Decision note |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for lesson in lessons:
        inventory, cefr, status, note = evidence_for(lesson)
        lines.append(
            f"| {lesson['id']} | {_cell(lesson['level'])} | {_cell(lesson['canDo'])} | "
            f"{_cell(inventory)} | {_cell(cefr)} | {_cell(_granular_result(lesson['no']))} | "
            f"{status} | {_cell(note)} |"
        )
    lines += [
        "",
        "## Next pass",
        "",
        "1. Feed native-review flags into the separate corpus/naturalness audit; do not rewrite the TOC here.",
        "2. Add another granular EGP result only when a native disposition or product band decision depends on it.",
        "3. Resolve Core 76 and 105 productive placement through representative lessons and delayed retrieval;",
        "   first-party form attestation alone does not certify their current bands.",
        "4. Keep learner-performance evidence elsewhere rather than widening this compact source ledger.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    lessons = track_parsers.parse_core()
    if set(UNIT_EVIDENCE) != {lesson["unitNo"] for lesson in lessons}:
        raise ValueError("unit evidence must cover every live Core unit exactly")
    if not set(ROW_OVERRIDES).issubset({lesson["no"] for lesson in lessons}):
        raise ValueError("row override references an unknown Core lesson")
    OUT.write_text(render(lessons), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parent)} — {len(lessons)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
