#!/usr/bin/env python3
"""Generate the authored-deck vocabulary ledger; lesson HTML remains authoritative."""

from __future__ import annotations

import pathlib
import re

import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import vocabulary


ROOT = pathlib.Path(__file__).resolve().parents[3] / "sandbox/drafts/en"
TRACKS = ROOT / "tracks"
OUT = ROOT / "reference" / "running-lexicon.md"
GENERATED = "Generated by `tools/authoring/en/build_running_lexicon.py` — do not edit this file."
REVIEW_ID = re.compile(r'<meta\s+name="podo:review-id"\s+content="([^"]+)"\s*/?>')


def decks() -> list[pathlib.Path]:
    return sorted(
        path for path in TRACKS.glob("*/courses/*/lessons/*/lesson.html")
        if "_archive" not in path.parts
    )


def lesson_number(path: pathlib.Path) -> int:
    match = re.match(r"(\d+)-", path.parent.name)
    if not match:
        raise vocabulary.VocabularyError(f"{path}: lesson directory must start with a number")
    return int(match.group(1))


def _items(entries: list[dict]) -> str:
    if not entries:
        return "—"
    return "<br>".join(
        f"`{entry['english']}` · {entry['japanese']}"
        + (f" ← {entry['source']}" if entry["source"] else "")
        for entry in entries
    )


def collect(paths: list[pathlib.Path]) -> list[dict]:
    records = []
    # Ownership is sense-specific.  The same surface form can be newly taught
    # again with a genuinely different Japanese meaning (for example,
    # ``open`` = 開いている vs 開ける).  Collapsing those senses would
    # create a false recycled dependency; repeating the same bilingual sense
    # is still an authoring error.
    owners: dict[tuple[str, str, str], tuple[str, pathlib.Path]] = {}
    for path in paths:
        text = path.read_text(encoding="utf-8")
        data = vocabulary.parse(text, source=path)
        if data["status"] != "reviewed":
            raise vocabulary.VocabularyError(
                f"{path}: vocabulary status is {data['status']!r}; finish the editorial pass first"
            )
        review_match = REVIEW_ID.search(text)
        if not review_match:
            raise vocabulary.VocabularyError(f"{path}: missing podo:review-id")
        record = {
            "path": path,
            "track": path.relative_to(TRACKS).parts[0],
            "number": lesson_number(path),
            "review_id": review_match.group(1),
            **data,
        }
        for entry in data["categories"]["new"]:
            key = (
                record["track"],
                entry["english"].casefold(),
                entry["japanese"].casefold(),
            )
            if key in owners:
                owner_review_id, owner_path = owners[key]
                # Accessible and full Freetalking decks are two language-load
                # renderings of one curricular topic. They share the same FT-N
                # ownership; counting their common vocabulary twice would force
                # one version to claim a false dependency on the other.
                if record["track"] != "3-freetalking" or record["review_id"] != owner_review_id:
                    raise vocabulary.VocabularyError(
                        f"{path}: {entry['english']!r} is also declared new by {owner_path}"
                    )
            else:
                owners[key] = (record["review_id"], path)
        records.append(record)
    return sorted(records, key=lambda item: (item["track"], item["number"], item["path"].as_posix()))


def render(records: list[dict]) -> str:
    lines = [
        "# Running English Lexicon",
        "",
        f"> **{GENERATED}**",
        ">",
        "> Lesson HTML owns the editorial classification. This file is a projection used to avoid",
        "> silently spending the same vocabulary twice or exceeding Core/Contextual's normal",
        "> 6–8-new-word load.",
        "",
        "## Contract",
        "",
        "- **New** counts productive content words first introduced by the lesson. Eight is the normal Core/Contextual ceiling.",
        "- **Recycled** names its earlier curriculum owner; it does not consume today's load.",
        "- **Assumed-known** is genuinely available without teaching, such as a transparent loanword.",
        "- **Receptive-only** may occur in tutor or partner speech but is not demanded from the learner.",
        "- Target-frame grammar and supporting expressions are tracked elsewhere and do not masquerade as content words.",
        "",
    ]
    if not records:
        lines += ["No authored English decks declare reviewed vocabulary yet.", ""]
        return "\n".join(lines)

    for track in sorted({record["track"] for record in records}):
        lines += [f"## `{track}`", "", "| Lesson | New | Recycled | Assumed-known | Receptive-only |", "| --- | --- | --- | --- | --- |"]
        for record in [item for item in records if item["track"] == track]:
            categories = record["categories"]
            count = len(categories["new"])
            label = record["path"].parent.name
            relative = record["path"].relative_to(ROOT)
            count_label = f"{count}/8 new" if track in {"1-core-patterns", "2-contextual-english"} else f"{count} new"
            lines.append(
                f"| [{label}](../{relative.as_posix()}) · **{count_label}** | "
                f"{_items(categories['new'])} | {_items(categories['recycled'])} | "
                f"{_items(categories['assumed'])} | {_items(categories['receptive'])} |"
            )
        lines.append("")

    lines += [
        "## Authoring rule",
        "",
        "Declare all four categories in the deck head and set `podo:vocabulary-status` to `reviewed`",
        "only after checking every learner-produced slot and hint chip. If a lesson genuinely needs more",
        "than eight new content words in Core or Contextual, add a non-empty `podo:vocabulary-waiver`;",
        "the deck checker will",
        "surface that exception for human review rather than hiding it.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    records = collect(decks())
    OUT.write_text(render(records), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT.parent)} — {len(records)} deck(s), {sum(len(x['categories']['new']) for x in records)} new word(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
