#!/usr/bin/env python3
"""Generate compact authoring briefs from every English TOC.

    python3 tools/authoring/en/build_lesson_briefs.py --all
    python3 tools/authoring/en/build_lesson_briefs.py 2-contextual-english

Briefs contain no independent curriculum facts. They make the source entry,
adjacent context and sequence constraints cheap to load during lesson writing.
"""

from __future__ import annotations

import argparse
import pathlib

import track_parsers


ROOT = pathlib.Path(__file__).resolve().parents[3] / "sandbox/drafts/en"
GENERATED = "Generated by `tools/authoring/en/build_lesson_briefs.py` — do not edit this file."


def _line(label: str, value: str | None) -> list[str]:
    return [f"- **{label}:** {value}"] if value else []


def _patterns(lesson: dict) -> list[str]:
    rows = []
    for i, model in enumerate(lesson.get("models", []), 1):
        rows += [f"### Pattern {i}", "", f"- **Model:** {model['model']}", f"- **Frame:** `{model['pattern']}`"]
        if model.get("partner"):
            rows.append(f"- **Partner:** {model['partner']}: {model['reaction']}")
        if model.get("coreRefs"):
            rows.append(f"- **Core ownership:** {', '.join(f'Core {n}' for n in model['coreRefs'])}")
        if model.get("chunk"):
            rows.append("- **Treatment:** teach as a bounded chunk; do not expand its grammar here")
        rows.append("")
    return rows


def _neighbors(lessons: list[dict], index: int) -> list[str]:
    prior = lessons[index - 1] if index else None
    following = lessons[index + 1] if index + 1 < len(lessons) else None
    return [
        f"- **Previous:** {prior['id']} · {prior['title']}" if prior else "- **Previous:** track opening",
        f"- **Next:** {following['id']} · {following['title']}" if following else "- **Next:** track ending",
    ]


def _core_guardrail(lessons: list[dict], index: int) -> list[str]:
    lesson = lessons[index]
    n = lesson["no"]
    recent = lessons[max(0, index - 3):index]
    upcoming = lessons[index + 1:index + 4]
    lines = [
        f"- **Already learned:** Core 1–{n - 1}." if n > 1 else "- **Already learned:** none; this is the opening lesson.",
        f"- **Not yet:** Core {n + 1}–122. Do not use their forms in learner-produced language." if n < 122 else "- **Not yet:** none inside Core.",
    ]
    if recent:
        lines.append("- **Most recent available forms:** " + " · ".join(f"{x['id']} {x['title']}" for x in recent))
    if upcoming:
        lines.append("- **Nearest protected forms:** " + " · ".join(f"{x['id']} {x['title']}" for x in upcoming))
    lines += [
        "- The readiness gate applies to the complete learner-produced model, including every fixed word.",
        "- Apart from this lesson's two taught patterns, productive grammar must come from earlier Core lessons.",
        "- At Pre-A1/A1, at most one explicitly declared bounded survival chunk may run ahead; keep it whole and do not transform or assess its internal grammar.",
        "- Tutor and partner English may run ahead only as supported receptive language; it must not become an unlabelled learner target.",
        "- Spiral review reuses the current can-do and does not add a third pattern or a second grammar explanation.",
    ]
    return lines


def render(track: str, lessons: list[dict], index: int) -> str:
    lesson = lessons[index]
    lines = [
        f"# {lesson['id']} · {lesson['title']}", "", f"> **{GENERATED}**", ">",
        "> The track TOC is authoritative. Fix it or the parser, then regenerate this brief.", "",
        "## Identity", "", f"- **Track:** `{track}`", f"- **Stable review id:** `{lesson['id']}`",
        f"- **Level:** {lesson.get('level', '—')}", "",
        "## Outcome", "",
    ]
    lines += _line("Can do", lesson.get("canDo"))
    if track == "1-core-patterns":
        lines += _line("Unit", f"{lesson['unitNo']} · {lesson['unit']}")
    elif track == "2-contextual-english":
        lines += _line("Practical area", f"{lesson['areaNo']} · {lesson['area']}")
        lines += _line("Course", f"{lesson['courseNo']} · {lesson['course']}")
        lines += _line("Scene", lesson["scene"])
        lines += _line("Entry floor", f"Core {lesson['floor']}")
    elif track == "3-freetalking":
        lines += _line("Theme", f"{lesson['themeNo']} · {lesson['theme']}")
        lines += _line("Format", " + ".join(lesson["formats"]))
        lines += _line("Opening", lesson["opening"])
        lines += _line("Question ladder", lesson["ladder"])
        lines += _line("Heavy topic", "`深く` — use after rapport exists" if lesson["deep"] else None)
    else:
        lines += _line("Part", f"{lesson['partNo']} · {lesson['part']}")
        lines += _line("Japanese habit", lesson["habit"])
        lines += _line("Correction target", lesson["fix"])
        lines += _line("Examples", lesson["examples"])

    if lesson.get("models"):
        lines += ["", "## Required production", ""] + _patterns(lesson)
    if track == "1-core-patterns":
        lines += ["## Supporting content", ""]
        lines += _line("Expressions", lesson["expressions"])
        lines += _line("Grammar", lesson.get("grammar") or "⚠ missing from the TOC; do not invent it inside a deck assignment")
        lines += _line("Fixed support", lesson.get("fixedSupport"))
        lines += _line("Bounded survival chunk", lesson.get("boundedChunk"))
        lines += _line("Japanese-L1 risk", lesson["jp"])
        if lesson["spiralReviews"]:
            lines += ["", "## Planned spiral review", ""]
            for review in lesson["spiralReviews"]:
                lines.append(f"- **{review['id']} · {review['mode']}:** {review['description']}")
    elif track == "2-contextual-english":
        lines += ["## Supporting content", ""]
        lines += _line("Expressions", lesson.get("expressions"))
        lines += _line("Receptive only", lesson.get("understand"))
        lines += _line("Author note", lesson.get("authorNote"))
    elif track == "3-freetalking":
        retrieval = []
        retrieval += _line("Moves", lesson.get("moves"))
        retrieval += _line("Core references", ", ".join(f"Core {n}" for n in lesson["coreRefs"]) or None)
        retrieval += _line("Shared source", lesson.get("shared"))
        if retrieval:
            lines += ["", "## Retrieval", ""] + retrieval

    lines += ["", "## Sequence guardrails", ""]
    if track == "1-core-patterns":
        lines += _core_guardrail(lessons, index)
    elif track == "2-contextual-english":
        refs = sorted({n for model in lesson["models"] for n in model["coreRefs"]})
        lines += [
            f"- **Assumed productive floor:** Core 1–{lesson['floor']}.",
            f"- **Pattern owners used here:** {', '.join(f'Core {n}' for n in refs) if refs else 'no exact Core owner; bounded situational chunks only'}.",
            "- A pattern more than two Core units above the floor must remain marked `chunk`; do not teach its grammar in this lesson.",
            "- Partner reactions and `Understand` are receptive; they do not add production targets.",
            "- This lesson is standalone. Do not invent plot history, callbacks, or a next-lesson teaser.",
        ]
    elif track == "3-freetalking":
        lines += [
            "- This track retrieves Core; it does not introduce a second grammar sequence.",
            "- Keep the same topic intent in both versions. Simplify language load, not intellectual interest.",
            "- The opening must still pass the three-second test in the learner's L1.",
        ]
    else:
        lines += ["- Planning only. Do not create a deck until the pronunciation track receives an explicit pilot approval."]

    lines += ["", "## Neighbouring items", ""] + _neighbors(lessons, index)
    lines += [
        "", "## Authoring inputs — read in order", "", "1. `../../../../ux-philosophy.md`",
        "2. `../../../AGENTS.md`", "3. `../../../LESSON-CREATION-WORKFLOW.md`",
        "4. `../lesson-blueprint.md` (must exist before this track's pilot)",
        "5. This brief", "6. The complete canonical deck named by the blueprint", "",
    ]
    return "\n".join(lines)


def build(track: str) -> int:
    lessons = track_parsers.parse_track(track)
    out = ROOT / "tracks" / track / "toc"
    out.mkdir(exist_ok=True)
    expected = set()
    index = [f"# {track} · generated lesson briefs", "", f"> **{GENERATED}**", ""]
    for i, lesson in enumerate(lessons):
        path = out / f"{lesson['id']}.md"
        path.write_text(render(track, lessons, i), encoding="utf-8")
        expected.add(path)
        index.append(f"- [`{lesson['id']}`]({path.name}) · {lesson['title']}")
    index_path = out / "index.md"
    index_path.write_text("\n".join(index) + "\n", encoding="utf-8")
    expected.add(index_path)
    stale = [p for p in out.glob("*.md") if p not in expected and GENERATED in p.read_text(encoding="utf-8")]
    if stale:
        raise SystemExit("stale generated briefs require explicit removal: " + ", ".join(str(p) for p in stale))
    print(f"{track}: wrote {len(lessons)} briefs -> {out.relative_to(ROOT.parent)}")
    return len(lessons)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("track", nargs="?", choices=sorted(track_parsers.PARSERS))
    parser.add_argument("--all", action="store_true")
    args = parser.parse_args()
    if not args.all and not args.track:
        parser.error("give a track name or --all")
    tracks = sorted(track_parsers.PARSERS) if args.all else [args.track]
    total = sum(build(track) for track in tracks)
    print(f"wrote {total} briefs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
