#!/usr/bin/env python3
"""Regenerate the Core grammar/function map from the authoritative TOC."""

from __future__ import annotations

import pathlib

import track_parsers


ROOT = pathlib.Path(__file__).resolve().parents[3] / "sandbox/drafts/en"
OUT = ROOT / "reference" / "grammar-coverage-map.md"
GENERATED = "Generated by `tools/authoring/en/build_grammar_map.py` — do not edit this file."


def cell(value: str | None) -> str:
    return (value or "").replace("|", "\\|").replace("\n", " ")


def render(lessons: list[dict]) -> str:
    missing_grammar = [lesson["no"] for lesson in lessons if not lesson["grammar"]]
    missing_summary = (
        f"{len(missing_grammar)} — Core {missing_grammar[0]}–{missing_grammar[-1]}"
        if missing_grammar
        else "0 — none"
    )
    grammar_status = (
        [
            "> **Open gap:** The rows named above have no authoritative `Grammar:` field. The",
            "> generator marks them rather than reverse-engineering an explanation from the patterns.",
        ]
        if missing_grammar
        else [
            "> **Complete:** Every Core row has an authoritative learner-facing `Grammar:` field.",
        ]
    )
    registry = lessons[0]["reviewRegistry"]
    lines = [
        "# Core Grammar and Function Coverage Map",
        "",
        f"> **{GENERATED}**",
        ">",
        "> The Core TOC is the source of truth. Fix curriculum facts there, then regenerate this map.",
        "",
        "This is an **author-only sequence audit**, not learner-facing material. It preserves the exact",
        "can-do, patterns, grammar support and Japanese-L1 risk currently written in the 122-lesson",
        "Core spine. The sequence guardrail is deliberately conservative: lesson N may assume Core",
        "1–N−1, while any narrower dependency claim requires evidence the TOC does not currently carry.",
        "",
        "## Coverage health",
        "",
        f"- **Lessons parsed:** {len(lessons)}",
        f"- **Lessons with two production patterns:** {sum(len(x['patterns']) == 2 for x in lessons)}",
        f"- **Lessons with a JP-risk note:** {sum(bool(x['jp']) for x in lessons)}",
        f"- **Lessons with learner-facing grammar support:** {sum(bool(x['grammar']) for x in lessons)}",
        f"- **Lessons with planned spiral review:** {sum(bool(x['spiralReviews']) for x in lessons)}",
        f"- **Planned review returns:** {sum(len(x['spiralReviews']) for x in lessons)} across {len(registry)} stable targets",
        f"- **Explicit bounded survival chunks:** {sum(bool(x['boundedChunk']) for x in lessons)}",
        f"- **Missing grammar support:** {missing_summary}",
        "",
        *grammar_status,
        "",
        "## Japanese-L1 spiral health",
        "",
        "| Target | Persistent difficulty | Introduced | Planned returns | Modes |",
        "| --- | --- | ---: | --- | --- |",
    ]
    for target, meta in registry.items():
        returns = [
            (lesson["no"], review["mode"])
            for lesson in lessons
            for review in lesson["spiralReviews"]
            if review["id"] == target
        ]
        lines.append(
            f"| `{target}` | {cell(meta['description'])} | Core {meta['introduced']} | "
            f"{' · '.join(f'Core {number} `{mode}`' for number, mode in returns)} | "
            f"{', '.join(sorted({mode for _number, mode in returns}))} |"
        )
    lines += [
        "",
        "## Sequence",
        "",
        "| Lesson | Unit / band | Communicative function | Two production patterns | Learner-facing grammar support | Bounded chunk | Spiral review | Sequence guardrail | Japanese-L1 risk |",
        "| ---: | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for lesson in lessons:
        patterns = "<br>".join(f"`{cell(pattern)}`" for pattern in lesson["patterns"])
        guardrail = "opening lesson" if lesson["no"] == 1 else f"may assume Core 1–{lesson['no'] - 1}"
        grammar = cell(lesson["grammar"]) if lesson["grammar"] else "⚠ **not specified in TOC**"
        bounded = cell(lesson["boundedChunk"]) or "—"
        spiral = " · ".join(f"`{x['id']}:{x['mode']}`" for x in lesson["spiralReviews"]) or "—"
        lines.append(
            f"| {lesson['no']} | Unit {lesson['unitNo']} · {cell(lesson['level'])} | "
            f"{cell(lesson['canDo'])} | {patterns} | {grammar} | {bounded} | {spiral} | "
            f"{guardrail} | {cell(lesson['jp'])} |"
        )
    lines += [
        "",
        "## Author audit rule",
        "",
        "A feature is introduced only when the learner uses it to complete the lesson can-do. A review",
        "return counts only when the learner retrieves it in the declared mode; a mention in an",
        "explanation or optional expression does not count. Contextual and Freetalking material may",
        "reuse a Core pattern or label a deliberately memorised chunk; it must not silently turn a later",
        "Core target into assumed productive grammar.",
        "",
        "Before changing a band, check the source hierarchy in",
        "[`curriculum-source-hierarchy.md`](./curriculum-source-hierarchy.md). This map records the current",
        "curriculum claim; it does not make that claim authoritative merely by tabulating it.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    lessons = track_parsers.parse_core()
    OUT.write_text(render(lessons), encoding="utf-8")
    missing_grammar = [lesson["no"] for lesson in lessons if not lesson["grammar"]]
    print(f"wrote {OUT.relative_to(ROOT.parent)} — {len(lessons)} rows; {len(missing_grammar)} grammar gaps surfaced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
