"""Independently authored Full and reciprocal follow-ups for FT107-121."""

FULL_FOLLOWUPS = {
    107: {
        "saved-time": ("What did the slower option save?", "When would paying more be worth it?"),
        "free-hours": ("How would the first hour begin?", "How would you keep the hours from filling up again?"),
        "choice": ("What would your choice make possible tomorrow?", "What is the best reason to choose the other option?"),
        "first-change": ("How urgent is the problem?", "Would a small amount make a real difference?"),
        "opposite": ("What would you do with the first extra hour?", "Would one free afternoon help more than an hour each day?"),
        "ten-hours": ("Which part of life would lose those hours?", "Would you answer differently if the schedule lasted only one month?"),
        "future": ("What would the extra time protect?", "Would you make the same choice for a short-term problem?"),
    },
    108: {
        "slow-talk": ("Which sign shows that a conversation has built trust?", "How does mutual attention matter more than its length?"),
        "crowd": ("Which social cue would make the first approach easier?", "How would the strategy change if nobody knew the host?"),
        "choice": ("Which need—belonging, information, or care—drives the choice?", "What would the preferred circle fail to provide?"),
        "daily-life": ("Which ordinary situation would reveal the limitation first?", "How would the same social structure affect loneliness?"),
        "opposite": ("Which transition gives the rejected network an advantage?", "Whose needs would make the opposite structure more suitable?"),
        "new-city": ("Would broad contacts or dependable care matter first?", "At what point would the other kind of friendship become necessary?"),
        "change": ("Which loss would expose a weakness in the chosen circle?", "Could one new responsibility reverse the preferred network?"),
    },
    109: {
        "hard-day": ("Which burden comes from temperature and which from infrastructure?", "Who would face the greatest health or mobility risk?"),
        "perfect-day": ("Which activity depends most on temperature rather than daylight?", "How would the ideal change if the day had to be productive?"),
        "choice": ("Which daily system would decide the climate choice?", "What seasonal experience would be hardest to lose?"),
        "daily-life": ("How would food, transport, and sleep adapt over time?", "Which change would become expensive rather than merely inconvenient?"),
        "comfortable-home": ("Which outdoor condition would remain impossible to control?", "Would reliable transport remove the stronger objection?"),
        "daylight": ("How much of the preference is actually about sleep or mood?", "Would equal daylight make humidity or ice more decisive?"),
        "switch": ("Which exact weather threshold would change the answer?", "Would the threshold differ for work and leisure?"),
    },
    110: {
        "clear-head": ("Which kind of task best reveals that peak?", "How stable is the pattern across workdays and free days?"),
        "free-day": ("How much would the chosen timing differ from the current one?", "Which part reflects sleep debt rather than a preferred rhythm?"),
        "choice": ("Which fixed commitment makes one rhythm more practical?", "What benefit of the rejected rhythm would still be valuable?"),
        "whole-day": ("Which shared activity would be hardest to coordinate?", "How would light exposure and meal timing shift together?"),
        "housemate": ("Which boundary around noise and light would be non-negotiable?", "Where would both schedules need a shared hour?"),
        "no-morning-duty": ("Would the new pattern remain stable after several weeks?", "What evidence would separate preference from recovery sleep?"),
        "switch": ("Which obligation could justify changing the body-clock routine?", "How gradually would the schedule need to move?"),
    },
    111: {
        "surprise": ("Which failed plan created access to something better?", "What kind of disruption would still ruin the trip?"),
        "first-decision": ("Which scarce item deserves commitment before anything else?", "What information would you wait to learn locally?"),
        "choice": ("Which risk makes advance planning valuable on this trip?", "Which discovery would require leaving space open?"),
        "month": ("How would repeated planning affect energy and attention?", "Which part of travel would become predictable in a bad way?"),
        "hotel-only": ("Which uncertainty would feel exciting and which would feel unsafe?", "What backup would make the open itinerary workable?"),
        "different-partner": ("Which decisions require shared consent rather than compromise?", "How would you divide control without creating resentment?"),
        "switch": ("Which destination feature would demand the opposite style?", "Would cost, access, or safety be the decisive factor?"),
    },
    112: {
        "alone-time": ("Which need is easier to notice when nobody else is present?", "How would you agree on separate time without causing concern?"),
        "share-view": ("What would the other person's presence add to the moment?", "Would sharing it later through a story preserve the same value?"),
        "choice": ("Which responsibility is hardest to carry alone in a new place?", "What form of autonomy would be lost with company?"),
        "every-trip": ("Which destination would expose the weakness of one fixed style?", "How would repeated solo or shared travel affect confidence?"),
        "new-country": ("Which unfamiliar system would create the greatest need for support?", "Would strong local language ability remove that concern?"),
        "planner": ("Would giving up logistics also mean giving up influence?", "Which decision would you refuse to delegate?"),
        "switch": ("Which companion quality matters more than the destination?", "At what duration would the social format become tiring?"),
    },
    113: {
        "convenience": ("Which service produces the largest weekly time saving?", "Could digital access replace physical proximity in that case?"),
        "window": ("What daily value does that view support?", "How much housing cost or travel time would the view justify?"),
        "choice": ("Which need—space, access, quiet, or community—decides the answer?", "What cost of the preferred setting would be hardest to absorb?"),
        "move": ("Which routine would improve immediately after the move?", "Which relationship or service would take longest to rebuild?"),
        "no-car": ("Which essential journey becomes the test case?", "Would reliable regional transport erase the difference?"),
        "small-town": ("Which remaining urban service would still justify city life?", "Would stronger local ties compensate for less variety?"),
        "switch": ("Which life-stage change would reverse the location choice?", "Would the reversal be permanent or linked to one responsibility?"),
    },
    114: {
        "outage": ("Which essential system depends on the connection?", "At what duration would inconvenience become a safety issue?"),
        "cool-day": ("Which offline activity would restore rather than consume attention?", "What communication duty would still need a backup?"),
        "choice": ("Which loss creates the more serious health or access risk?", "What alternative infrastructure would make the other loss manageable?"),
        "first-problem": ("Who besides you would be affected by the first failure?", "Which backup would delay that failure longest?"),
        "cool-spring": ("Does removing heat risk reveal a different priority?", "Which online duty would be impossible to postpone?"),
        "safe-place": ("What hours and transport would make public cooling genuinely usable?", "Which household member would still be unable to rely on it?"),
        "switch": ("Which temperature or outage duration is the real threshold?", "How would humidity or medical risk change that threshold?"),
    },
    115: {
        "good-rest": ("Which boundary prevents work from occupying the day off mentally?", "How would care or household duties alter the idea of rest?"),
        "protected-time": ("Which relationship or health need depends on that period?", "What workplace rule could keep it protected?"),
        "choice": ("Which unmet need makes time or compensation more urgent?", "What minimum condition would the rejected offer still have to meet?"),
        "only-one": ("Which improvement would appear first and which cost would arrive later?", "Would the benefit remain valuable after a full year?"),
        "nights-weekends": ("Which recurring commitment makes those hours irreplaceable?", "What duration or compensation would make the sacrifice temporary?"),
        "one-year": ("Which measurable goal would justify the period of imbalance?", "What recovery plan would be required before accepting it?"),
        "switch": ("Which responsibility creates a genuine deadline for the decision?", "Would the new choice last after that responsibility ended?"),
    },
    116: {
        "distraction": ("Is the interruption caused by space, people, or digital habits?", "Which environmental change would remove it without moving?"),
        "commute-time": ("Which activity would reliably claim the recovered time?", "Would the benefit survive if home working created longer hours?"),
        "choice": ("Which task characteristic determines the better setting?", "What resource available in the other place would still matter?"),
        "one-place": ("Which learning or relationship cost would appear over time?", "How would the same location affect boundaries after six months?"),
        "quiet-office": ("Would proximity to colleagues add value beyond the quiet room?", "Which remaining office rule could still make home preferable?"),
        "team-day": ("Which decisions require synchronous contact on that day?", "How would the team preserve informal learning during the rest of the week?"),
        "switch": ("Which security, access, or collaboration need would force the move?", "Would the change apply to every task or only one category?"),
    },
    117: {
        "best-focus": ("Which feature supports beginning and which supports persistence?", "How would the ideal setting change for a different task?"),
        "one-hour": ("Which source of friction must disappear during that hour?", "Would public accountability outweigh full control of the room?"),
        "choice": ("Which cognitive demand makes one setting better for two hours?", "What advantage of the rejected place would remain useful?"),
        "one-month": ("Which context cue would become automatic by the end of the month?", "What new distraction or cost would accumulate over time?"),
        "drink-cost": ("How would repeated spending compare with the value of reliable focus?", "At what frequency would the café stop being worthwhile?"),
        "home-desk": ("Which remaining social or motivational benefit would the café keep?", "Would stronger boundaries at home be enough to sustain the change?"),
        "switch": ("Which task requires the privacy or equipment of the other place?", "Would session length change the preferred level of stimulation?"),
    },
    118: {
        "photo-match": ("Which evidence reduces uncertainty without relying on popularity?", "How would you verify the seller rather than only the product?"),
        "urgent": ("Which failure—delay, wrong fit, or higher price—is least acceptable today?", "Would confirmed local stock outweigh a wider online range?"),
        "choice": ("Which product feature needs direct inspection before purchase?", "What total cost would make the other channel more attractive?"),
        "only-one": ("Which missing source of information would cause the first mistake?", "How would accessibility differ for someone without easy transport?"),
        "cheap-return": ("What probability of a poor fit would erase the saving?", "Which return condition must be known before ordering?"),
        "same-day": ("Which service or expertise would still justify the physical shop?", "Would privacy or seller accountability affect the answer?"),
        "switch": ("Which combination of urgency and uncertainty changes the channel?", "Would the cost of a wrong choice matter more than the price?"),
    },
    119: {
        "photo-memory": ("Which sensory detail seems to reactivate the memory?", "How could later knowledge have changed the recalled scene?"),
        "small-moment": ("Which meaning would make the ordinary detail valuable later?", "Would an external record preserve what memory might lose?"),
        "choice": ("Which benefit depends on continuity and which on relief?", "What form of support could reduce the cost of either choice?"),
        "work-study": ("Would perfect recall improve judgment or only access to detail?", "Which kind of mistake might become harder to move beyond?"),
        "all-vivid": ("How would unimportant pain compete with useful information?", "Would control over when memories appear change the choice?"),
        "lost-lesson": ("Which part of the lesson could be preserved outside memory?", "How would agency change the value of forgetting?"),
        "switch": ("Which distinction between fact, feeling, and identity is decisive?", "Would the answer differ for recent and distant memories?"),
    },
    120: {
        "private-pride": ("Which value remains even without an audience?", "How would recognition change the reason for doing it?"),
        "anonymous-help": ("Which form of accountability should remain even without a name?", "Could anonymity increase trust in the contribution itself?"),
        "choice": ("Which need—security, influence, privacy, or belonging—drives the answer?", "What hidden cost of the preferred life is easiest to ignore?"),
        "daily-life": ("Which relationship would be most altered by wealth or reputation?", "How would ordinary decisions reveal the chosen value?"),
        "constant-rating": ("Which kind of scrutiny would turn respect into a burden?", "Could boundaries preserve influence without constant exposure?"),
        "family-knows": ("Would secrecy change trust inside the family?", "Which responsibility would come with sharing the information?"),
        "switch": ("Which level of visibility removes control over ordinary life?", "Would financial insecurity or reputational pressure reverse the choice first?"),
    },
    121: {
        "recent-skill": ("Which feedback changed the practice most effectively?", "What evidence shows that the improvement can transfer?"),
        "three-skills": ("Which skill frames the problem and which delivers the result?", "Where would specialist depth still be indispensable?"),
        "choice": ("Which future task rewards the chosen learning shape?", "What maintenance cost comes with the path you rejected?"),
        "one-year": ("How would exploration and deliberate practice divide the year?", "Which milestone would justify narrowing or widening the plan?"),
        "team": ("Which role connects specialist knowledge across the team?", "How would the ideal mix change under time pressure?"),
        "new-field": ("Which foundation must be broad before specialisation begins?", "What evidence would show that it is time to commit?"),
        "switch": ("Which task complexity or deadline reverses the strategy?", "Would access to a strong team change the required personal breadth?"),
    },
}

RECIPROCAL_FOLLOWUPS = {
    107: (("What did you agree on?", "What was different about your reasons?"), ("Where did your reasons overlap?", "Which difference mattered most?")),
    108: (("What mattered most in your tutor's choice?", "How was their reason different from yours?"), ("How does the tutor distinguish a contact from a close friend?", "Which transition would reverse their preferred circle?")),
    109: (("What kind of weather bothers your tutor most?", "Would better housing change their choice of season?"), ("Does the tutor weigh climate or infrastructure more heavily?", "Which temperature or daylight threshold reverses their answer?")),
    110: (("When does your tutor say they think most clearly?", "What fixed part of their day affects that choice?"), ("How much of the tutor's rhythm is biological rather than imposed?", "Which fixed commitment would reverse their preference?")),
    111: (("What does your tutor always book first?", "Which part of a trip do they leave open?"), ("How does the tutor separate necessary planning from unnecessary control?", "Which travel risk would reverse their style?")),
    112: (("Which travel responsibility does your tutor prefer to share?", "What freedom would they protect when travelling together?"), ("How does the tutor balance autonomy with practical support?", "Which destination or companion would reverse their answer?")),
    113: (("Which daily convenience matters most to your tutor?", "What would they miss in the other setting?"), ("How does the tutor value access against space and quiet?", "Which life-stage change would reverse their location choice?")),
    114: (("Which loss would be harder for your tutor?", "What other safe option would help them?"), ("How does the tutor separate convenience from essential infrastructure?", "Which safety condition would reverse their summer choice?")),
    115: (("Which part of personal time would your tutor protect?", "What would make higher pay worth the cost?"), ("How does the tutor distinguish compensation from sustainable work?", "Which responsibility would reverse their preferred offer?")),
    116: (("Which task would your tutor rather do in person?", "How would they use the time saved from commuting?"), ("How does the tutor assign location according to task purpose?", "Which workspace condition would reverse their preference?")),
    117: (("Which study task would your tutor take to a café?", "What makes home difficult for them?"), ("How does the tutor match stimulation and control to the task?", "Which change in equipment or routine would reverse their setting?")),
    118: (("Which product would your tutor never buy online?", "When would convenience matter more to them than seeing the product first?"), ("How does the tutor price uncertainty and return friction?", "Which service or delivery condition would reverse their channel?")),
    119: (("Which ordinary memory would your tutor want to keep clear?", "What problem with remembering everything worries them most?"), ("How does the tutor weigh continuity against relief?", "Which kind of memory would reverse their answer?")),
    120: (("Does your tutor value privacy or recognition more?", "What would they do with the chosen advantage?"), ("How does the tutor separate respect from public visibility?", "Which level of security or scrutiny would reverse their answer?")),
    121: (("Which skill would your tutor choose to master?", "Where would they prefer broader ability?"), ("How does the tutor balance exploration with deliberate practice?", "Which future task would reverse their learning strategy?")),
}

# FT107 still carries independently authored Full follow-ups.  Keep them as
# immediate as the shared Accessible/Full pairs and end each set with a route
# that does not depend on the learner's first answer.
FULL_FOLLOWUPS[107].update({
    "saved-time": ("What did the slower option save money on?", "Which usually costs less: walking or public transport?"),
    "free-hours": ("What would you do first?", "Which sounds better today: rest, errands, or fun?"),
    "choice": ("What would your choice make possible tomorrow?", "Which disappears faster in a busy week: money or free time?"),
    "first-change": ("How urgent would that cost be?", "What's one everyday expense that often surprises people?"),
    "opposite": ("What would you do with the first extra hour?", "Which helps more after a tiring week: extra time or extra money?"),
    "ten-hours": ("Which part of life would lose those hours?", "Would you give up one evening a week for higher pay?"),
    "future": ("What would the extra time protect?", "Which would you protect first: sleep or income?"),
})

_THREE_SECOND_RECIPROCAL_FOLLOWUPS = {
    107: ("Which part of your tutor's reason made sense to you?", "Which option would help more on a very busy day?"),
    108: ("What mattered most in your tutor's choice?", "Which is easier to build first: one close friendship or many contacts?"),
    109: ("What kind of weather bothers your tutor most?", "Would good heating or good air conditioning change the choice?"),
    110: ("When does your tutor think most clearly?", "Would a free weekend change the answer?"),
    111: ("What does your tutor always book first?", "Would they plan more for an expensive trip?"),
    112: ("Which travel responsibility does your tutor prefer to share?", "Would they travel alone for just one day?"),
    113: ("Which daily convenience matters most to your tutor?", "Would a shorter commute change the choice?"),
    114: ("Which loss would be harder for your tutor?", "Would a cooler climate change the choice?"),
    115: ("Which part of personal time would your tutor protect?", "Would a one-year offer change the choice?"),
    116: ("Which task would your tutor rather do in person?", "Would a long commute change the answer?"),
    117: ("Which study task would your tutor take to a cafe?", "Would a video call change the choice?"),
    118: ("Which product would your tutor never buy online?", "Would free returns change the answer?"),
    119: ("Which ordinary memory would your tutor want to keep clear?", "Would the choice change if only happy memories stayed vivid?"),
    120: ("Does your tutor value privacy or recognition more?", "Would the choice change if fame meant no privacy?"),
    121: ("Which skill would your tutor choose to master?", "Would six months to learn change the answer?"),
}
for _number, _followups in _THREE_SECOND_RECIPROCAL_FOLLOWUPS.items():
    RECIPROCAL_FOLLOWUPS[_number] = (_followups, _followups)
